### ISSUE TITLE
Dificuldades em baixar o Repositorio da aula 7

### ISSUE THREAD

**Issue by michaelmdxt** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#10]

**Comment by michaelmdxt** [comment]
Bruno, estou tendo certa dificuldade em clonar o repositorio no meu git bash, quando efetuo o comando " $git clone git@github.com:michaelmdxt/hxphp.git " aparece a seguinte mensagem:

$ git clone git@github.com:michaelmdxt/hxphp.git sistema
Cloning into 'sistema'...
The authenticity of host 'github.com Alterado para post ->(123.45.678.123)' can't be established.
RSA key fingerprint is (*****************************)<- aqui tinha uma chave alterei para postar.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,123.45.678.123' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Obrigado e parabéns pelo seu conteúdo extremamente de qualidade.

**Comment by brunosantoshx** [comment]
Olá @michaelmdxt, como vai?

Como está clonando o repo com todas as configurações será necessário subir sua chave ssh pública nas configurações do Github.

**Comment by michaelmdxt** [comment]
Olá Bruno, vc tem uma serie falando nisso? 
Ou pode me dizer quais a sequencia de comando que eu digito no git para subir a chave ?

Obrigado, e meus parabéns e sucesso.
