### ISSUE TITLE
Compatibilidade com PHP 7.0.4

### ISSUE THREAD

**Issue by EnioVedovatto** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#11]
Bruno, estou usando o PHP 7.0.4, mas quando clico em "Cadastrar" da página Cadastro de Usuarios, me retorna o seguinte "Fatal error: Uncaught ActiveRecord\UndefinedPropertyException: Undefined property: User->Array in C:\wamp64\www\loja\vendor\php-activerecord\php-activerecord\lib\Model.php on line 533 in C:\wamp64\www\loja\vendor\php-activerecord\php-activerecord\lib\Model.php on line 533", tive que usar o PHP da versão 5.6.19, como pode ser resolvido?

**Comment by brunosantoshx** [comment]
Olá @EnioVedovatto, como vai?

Este é um problema no PHP ACTIVERECORD, isto é, a versão atual ainda não está adaptada para o PHP7, porém, se analisar a lista de PRs do repo oficial, verá que já existem propostas de correção e você mesmo pode aplicar no seu código. Caso contrário, fique atento ao repo e atualize as dependências pelo Composer ou retroceda a versão do seu PHP.

Forte abraço e sucesso sempre!
