### ISSUE TITLE
Pagina Administrativa

### ISSUE THREAD

**Issue by EnioVedovatto** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#12]
Bruno, será que poderia acrescentar nesta serie a página administrativa?

**Comment by KLEITONFREITAS** [comment]
Ótima ideia, gosto do perfil de instrutor do Bruno.

**Comment by brunosantoshx** [comment]
Olá @EnioVedovatto e @KLEITONFREITAS. Como vão?

Pretendo abordar isto em uma série futura. O que acham?

Sei que estou demorando para postar novas aulas, mas é que estou passando por um momento muito caótico que não está me dando folga, porém creio que logo conseguirei conciliar as minhas novas responsabilidades e retomar com força total ao canal.

Forte abraço e sucesso sempre!
