### ISSUE TITLE
HXPHP Com VIrtualHost

### ISSUE THREAD

**Issue by KLEITONFREITAS** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#13]
Bom dia Pessoa!

sei que no curso de Criando cadastro e login, não foi abordado, eu não tive o que fazer e ativei o Virtualhosts no Apache, agora o problema, quando utilizo o endereço localhost/[NOMEDOPROJETO]
abre bonitinho dizendo que o HPPHP foi instalado corretamente até ai tudo bem "ainda estou na aula 7 faltando pouco para terminar" porem quando utilizo via virtualhosts só me aparece o texto puro  porem nada de CSS,JS ou que foi usado no HXPHP Framework.

ex:

Uhull! Você instalou e configurou o HXPHP Framework com sucesso!

Agora acesse a área de membros e assista ao nosso curso oficial para dominar completamente esta poderosa ferramenta.
HXPHP 2016 © - Todos os direitos reservados.

existe solução?

OBS: Sou novo na area de PHP e esse Canal do Youtube esta me ensinando muito mesmo.

Desde já agradeço qualquer ajuda.

**Comment by brunosantoshx** [comment]
Olá @KLEITONFREITAS, como vai?

Nunca presenciei este erro anteriormente, portanto não sei um caminho exato para corrigi-lo, porém, creio que o primeiro passo é verificar o caminho dos arquivos e validar a existência dos mesmos e, após isto, verifique se os arquivos não estão com problemas de permissões (é muito comum! o famoso erro 403). 

Se estiver utilizando Linux ou OSX é muito provável que esteja com problemas de permissão!

Fico no aguardo dos seus comentários.
Forte abraço e sucesso sempre!
