### ISSUE TITLE
Problema ao tentar logar

### ISSUE THREAD

**Issue by Rabbitss** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#14]
Acompanhei a serie toda atentamente e gostei bastante, mas quando fui tentar fazer o login no sistema apareceu o seguinte erro: Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sistemahx.login_attempts' doesn't exist' in C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php:322 Stack trace: #0 C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(322): PDOStatement->execute(Array) #1 C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\adapters\MysqlAdapter.php(25): ActiveRecord\Connection->query('SHOW COLUMNS FR...') #2 C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(264): ActiveRecord\MysqlAdapter->query_column_info('`login_attempts...') #3 C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(402): ActiveRecord\Connection->columns('`login_attempts...') #4 C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Cache.php(73): ActiveRecord\Table->ActiveRecord\{closure}() #5 in C:\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 325. nao sei o que fazer

**Comment by brunosantoshx** [comment]
Olá @Rabbitss, como vai?

Observe este trecho do erro:
**Table 'sistemahx.login_attempts' doesn't exist' **

Verifique seu banco de dados e confira se a tabela e o model de tentativas estão corretos.

Forte abraço e sucesso sempre!
