### ISSUE TITLE
composer/activeRecord

### ISSUE THREAD

**Issue by ianpjs** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#15]
Olá, primeiro eu gostaria de agradecer pela série que você produziu, ela é realmente incrível.

Eu estou com um problema, desde que eu dei o fork como você recomendou em uma das aulas, sempre que aperto o botão "cadastrar" a seguinte mensagem de erro aparece:

Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php:249 Stack trace: #0 C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(249): PDO->__construct('mysql:host=loca...', 'root', NULL, Array) #1 C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(111): ActiveRecord\Connection->__construct(Object(stdClass)) #2 C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\ConnectionManager.php(33): ActiveRecord\Connection::instance('mysql://root:@l...') #3 C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(114): ActiveRecord\ConnectionManager::get_connection(NULL) #4 C:\Users\Publ in C:\Users\Public\Documents\xampp\htdocs\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 251

O que poderia ser esse erro e como arrumá-lo ?

**Comment by brunosantoshx** [comment]
Olá @ianpjs, como vai?

O problema é que os dados de conexão com o banco de dados do repositório oficial são diferentes dos do seu projeto. Atualize as credenciais no arquivo de configuração e tudo deverá funcionar corretamente.

Forte abraço e sucesso sempre!
