### ISSUE TITLE
Montar menu dinâmico

### ISSUE THREAD

**Issue by ERomagnoli** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#16]
Bruno, @brunosantoshx 
Você poderia incrementar um pouco mais essa série e nos mostrar como montar um menu dinâmico com base em um cadastro no banco de dados. Assim seria possível dar permissões para cada usuário que for logar há um menu personalizado.

Obrigado

**Comment by brunosantoshx** [comment]
Opa @ERomagnoli, como vai?

Estive trabalhando nos últimos dias em uma atualização do MenuHelper para cumprir justamente este objetivo. A nova versão já está estável e será abordada na série após a conclusão do processo de redefinição de senha.

Iremos entender os níveis de acesso e exibir menus customizados de acordo com os mesmos. Também vamos explorar o bloqueio de páginas para níveis específicos e muito mais!

É só aguardar que em breve já teremos este conteúdo!

Abração!
