### ISSUE TITLE
Erro ao clonar pasta sistema da Aula 07

### ISSUE THREAD

**Issue by lucas-martins** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#17]
Comecei a acompanhar o curso há algumas semanas e estou na aula 7 e na hora de clonar aparecer o seguinte erro:

Cloning into 'sistema'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? #

Como faço pra resolver?

**Comment by brunosantoshx** [comment]
Olá @lucas-martins, como vai?

Não é um erro. Você precisa digitar `yes` e dar ENTER. 

Abração!
