### ISSUE TITLE
erro de login

### ISSUE THREAD

**Issue by livio13** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#18]
Ola
Comecei a acompanhar o curso há algumas semanas e estou na aula 8 e na hora de colocar Username certo e a senha errada  parecer o seguinte erro:

**((Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2016-05-03 01:04:16 BRT' for column 'created_at' at row 1' in C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 325))**

mais se eu colocar a senha correta e o Username errado nada acontece.

**Comment by brunosantoshx** [comment]
Olá @livio13, como vai?

O erro está ocorrendo na coluna `created_at`. E ele ocorre quando a senha está incorreta porque é quando a tabela `login_attempts` entra em ação. Confira o tipo de dado da coluna `created_at` da tabela `login_attempts`.

Forte abraço e sucesso sempre!

**Comment by KDuh** [comment]
Eu estou com esse mesmo problema, e a minha tabela está criada de acordo com a do curso nas primeiras aulas, tipo de dados TIMESTAMP e com predefinição de "CURRENT_TIMESTAMP", porém pelo que encontrei vasculhando a internet trata-se de um erro dentro do MySQL que não aceita a inserção do CURRENT_TIMESTAMP precisando ser, ao que parece, tratado pelo PHP antes da incersão no banco. Sendo assim, como esse tratamento pode ser feito?

**Comment by lucasrest** [comment]
Boa tarde, 

Estou com o mesmo problema do KDuh, alguém conseguiu resolver?
