### ISSUE TITLE
Olá Bruno!

### ISSUE THREAD

**Issue by fabianofs** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#21]
Bruno, enviei o sistema para o meu servidor de production online, e me aparece esse fatal erro. já atualizei as informações do banco de dados e continua com o erro, vc pode me ajudar? 
Fatal error: Class 'PDO' not found in /home/fselegance/public_html/admc/vendor/php-activerecord/php-activerecord/lib/Connection.php on line 111

**Comment by brunosantoshx** [comment]
Olá @fabianofs, como vai?

Seu servidor não está com a extensão PDO habilitada. Se for um VPS ou Dedicado, você pode habilitar pelo EasyApache, porém, se for hospedagem compartilhada, recomendo acionar o suporte.

Forte abraço e sucesso sempre!

**Comment by fabianofs** [comment]
Tudo bem Bruno, e com você?
Só estou quebrando a cabeça com esse sistema, no localhost funciona, no servidor online não funciona. Não sei lidar com o EasyApache.
Mesmo assim valeu!

Forte abraço!!

**Comment by fabianofs** [comment]
Olá Bruno! Tudo bem, e com você?
Conseguir resolver esse pequeno problema, atualizei a versão do php no servidor e vu alar!

Forte abraço e sucesso sempre!

Obrigado!

**Comment by brunosantoshx** [comment]
Opa, melhor agora! Show!

Qualquer dúvida é só chamar!
