### ISSUE TITLE
Serviço de autenticação não está funcionando

### ISSUE THREAD

**Issue by caiorcferreira** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#22]
Boa noite, eu estou acompanhando o projeto do Sistema de cadastro e login com níveis de acesso através do canal HxTutors no youtube.

Entretanto, ao seguir o projeto na aula 7, o cadastro continua a funcionar normalmente, inserindo os usuários no banco de dados, porém, após efetuada a operação a página não é redirecionada para a URL definida como 'after_login'.

Alguém poderia ajudar?
Caso seja necessário ver algum código avise-me qual.

Obrigado!

**Comment by gabiantunes** [comment]
Olá, estou com o mesmo problema...após clicar em cadastrar, o sistema registra o cadastro no banco de dados, mas no browser ele redireciona para o endereço de erro localhost/sistema/home/ e não para a página "pós cadastro". O pior é que após clicar em cadastrar esse erro permanece nas outras páginas também, como localhost/sistema/cadastro/cadastrar/ . Alguma ajuda? :(

**Comment by brunosantoshx** [comment]
Olá @caiorcferreira, como vai? 

Creio que o seu problema deva estar relacionado ao parâmetro `redirect` do serviço de autenticação, isto é, por padrão não é configurado para redirecionar e você precisa informar o booleano true. 

Recomendo que compare os arquivos via Github. Isso já deve resolver!

Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Olá @gabiantunes, como vai?

Isto é temporário e na próxima aula já será corrigido. É que ainda não criamos o HomeController e o sistema sempre vai redirecionar quando o usuário está autenticado e é por isso que já criamos a action sair para prosseguir com o desenvolvimento dos outros módulos do site. 

Forte abraço e sucesso sempre!
