### ISSUE TITLE
[Aula12_Parte2] - Não atualiza a nova senha

### ISSUE THREAD

**Issue by ERomagnoli** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#23]
Na aula 12 Parte 2 ja no final, quando digitamos a nova senha, na explicação do video deveria aparecer a mensagem "Sua senha foi redefinida com sucesso". Porém no meu caso, aparece a mensagem "Código invalido ou expirado".

Estou anexando os meus arquivos RecuperarController, User, Redefinir, Recovery e os prints de erros.
O que observei de estranho, foi que no link "token" ao clicar no botão "Alterar minha senha", no endereço URL apareceu na frente do token %20 como pode observar na imagem anexa.

Obrigado
[Erros Video12P2.zip](https://github.com/brunosantoshx/serie-criando-sistema-de-cadastro-e-login/files/276340/Erros.Video12P2.zip)

**Comment by brunosantoshx** [comment]
Olá @ERomagnoli, como vai?

O problema está no token informado. Esse caractere mencionado é a substituição de um espaço quando a URL é codificada. Você pode conferir aqui: http://www.w3schools.com/tags/ref_urlencode.asp

Recomendo que você copie e cole novamente o token e certifique-se que não exista nenhum espaço em branco no final. 

Fico no aguardo.
Forte abraço e sucesso sempre!
