### ISSUE TITLE
[Aula 5] - Gravação da Senha

### ISSUE THREAD

**Issue by camposfabio** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#24]
Na aula 5 a validação da senha não funciona pois sempre está sendo gerada uma senha hash pelo sistema.
Acho que seria mais correto utilizar o código abaixo em User.php:
**if (!empty($post['password'])) {**					
	$password = \HXPHP\System\Tools::hashHX($post['password']);	
	$post = array_merge($post, $password);
**};**

Um abraço

Fabio

**Comment by brunosantoshx** [comment]
Olá @camposfabio, como vai? 

Ué, que estranho! Não temos a validação via `presence_of`? Você verificou se o campo `password` está com algum valor atribuído quando o formulário é enviado?

Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by camposfabio** [comment]
Olá Foi falha minha. Eu havia desligado a obrigatoriedade para o teste. 
Um abraço

Fabio
