### ISSUE TITLE
Registrar último acesso

### ISSUE THREAD

**Issue by gabiantunes** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#26]
Olá!! Gostaria de saber como criar uma tabela para gravar a data e horário do ultimo login dos usuários, como eu modulo ela no Workbench? Obrigada!﻿

**Comment by carusogabriel** [comment]
Não seria mais interessante criar um campo na tabela `users` chamado `last_login` do tipo `timestamp`, assim  seria só tratar esse dado no PHP e obter esta informação?

**Comment by gabiantunes** [comment]
Então..na verdade eu fiz isso, mas o sistema está registrando quando foi feito o cadastro, e não o último login :(

**Comment by brunosantoshx** [comment]
Olá @gabiantunes, como vai? Você vai precisar trabalhar com o `update` deste campo toda vez que o usuário for autenticado. 

Algo assim deve resolver:

```php
$user = User::find($login->user->id); //Variável login com o $callback_obj
$user->last_login = date('Y-m-d H:i:s');
$user->save(false);

$this->auth->login(...);
```

Espero ter ajudado.
Forte abraço e sucesso sempre!

**Comment by gabiantunes** [comment]
Ola, sou eu denovo. Obg pela resposta, vi que finalizou a serie e resolvi tentar mais uma vez. Minha duvida é: devo adicionar esse código que você me passou na página "UsuariosControllers" ou "LoginControllers"? E em que parte da pagina devo adicionar? Obrigada!
