### ISSUE TITLE
Fatal error Acesso página login/cadastro - Site online Hostinger 

### ISSUE THREAD

**Issue by duducp** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#28]
Boa noite, fiz o upload do site seguindo a vídeo aula 12 no youtube, mas quando acesso as página de login/cadastro/recuperar está me mostrando o seguinte erro:

`Fatal error: Uncaught exception 'Exception' with message 'Verifique as configuracoes de autenticacao para a subpasta: < default >' in /home/u912798111/public_html/src/HXPHP/System/Services/Auth/Auth.php:54 Stack trace: #0 [internal function]: HXPHP\System\Services\Auth\Auth->__construct(NULL, NULL, true) #1 /home/u912798111/public_html/src/HXPHP/System/Controller.php(106): ReflectionClass->newInstanceArgs(Array) #2 /home/u912798111/public_html/app/controllers/CadastroController.php(14): HXPHP\System\Controller->load('Services\\Auth', NULL, NULL, true) #3 /home/u912798111/public_html/src/HXPHP/System/App.php(90): CadastroController->__construct(Object(HXPHP\System\Configs\Config)) #4 /home/u912798111/public_html/index.php(33): HXPHP\System\App->run() #5 {main} thrown in /home/u912798111/public_html/src/HXPHP/System/Services/Auth/Auth.php on line 54`

Não intendi muito bem o erro, mas pode ser uma falha na conexão com o banco de dados?

**Comment by duducp** [comment]
Bom a causa do erro é o seguinte. No app/config da serie você utiliza array para poder conectar ao Banco de dados, já no HXPHP na versão mais recente, você não utiliza array e sim []. Mudei no meu arquivo para a conexão utilizando array e funcionou. A versão do php do servidor é a 5.6.

**Comment by brunosantoshx** [comment]
Olá @duducp, como vai?

Caramba, que estranho! Essa marcação simplificada para arrays é um recurso antigo e deveria funcionar perfeitamente na versão do seu servidor. Porém, agradeço o seu retorno e acredito que se acabar se repetindo com outras pessoas a sua resposta vai salvá-las da dor de cabeça. 

Obrigadão!
Forte abraço e sucesso sempre!
