### ISSUE TITLE
Erro ao acessar diretamente "redefinir ou alterar-senha"

### ISSUE THREAD

**Issue by duducp** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#29]
Boa noite, percebi que ao acessar diretamente sistema/recuperar/redefinir e sistema/recuperar/alterar-senha, ocorre um erro pois essas funções não estão recebendo o valor do token pois ele é nulo.

**Comment by brunosantoshx** [comment]
Olá @duducp, como vai?

Então... na teoria estes links não devem ser acessados sem o token, mas é possível passar um valor padrão diretamente nos argumentos do método e assim a validação já acusará o código expirado/inválido.

Forte abraço e sucesso sempre!
