### ISSUE TITLE
Erro ao realizar a troca da senha

### ISSUE THREAD

**Issue by duducp** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#30]
Boa noite, quando realizamos a troca da senha está configurado para sermos redirecionados para a página de login, mas o mesmo não está acontecendo e gerando um erro. Veja a imagem abaixo:
![captura de tela 27](https://cloud.githubusercontent.com/assets/16366240/15983147/6eb277cc-2f74-11e6-9132-55e4da8ab1f4.png)

**Comment by brunosantoshx** [comment]
Olá @duducp, como vai?

Acabei de enviar uma correção para o repositório oficial. Peço que você atualize o HXPHP e teste para verificar se o problema permanece. 

Fico no aguardo.
Abração!

**Comment by duducp** [comment]
Bom dia @brunosantoshx problema corrigido!

Obrigado!
