### ISSUE TITLE
Problema na atualização do HXPHP

### ISSUE THREAD

**Issue by fabianofs** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#32]
Olá Bruno, tudo bem?

Eu atualizei o HXPHP trocando a pasta src, porem deu erro no arquivo de redefinição de senha, informando quer o template não foi encontrado. Qual o procedimento para que eu possa resolver esse erro?

Obrigado pela atenção.

Aguardando um retorno.

Atenciosamente

Fábio Souza

Sucesso sempre!

**Comment by brunosantoshx** [comment]
Olá @fabianofs, como vai?

É que nesta nova versão do HXPHP a pasta de templates fica na raiz. Você precisa copiar a pasta `templates` junto com a pasta `src`.

Abração e sucesso sempre!

**Comment by fabianofs** [comment]
Olá Bruno Santos, como vai?
Tudo bem Bruno, obrigado!
Bruno, segui a instrução que você me passou, porem, não resolveu. Quando colto para as configuração anterior funciona normalmente. Mas mesmo assim obrigado!

Valeu Bruno, sucesso sempre!

**Comment by brunosantoshx** [comment]
Olá @fabianofs, boa noite. 

Acho que não expliquei corretamente hehehe. Existe uma nova pasta `templates` na raiz do repositório. Você precisa copiar ela junto com a pasta `src` para tudo funcionar perfeitamente.
