### ISSUE TITLE
Dúvida - Sincronizando com o repositório 

### ISSUE THREAD

**Issue by LarissaSouza** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#34]
Olá Bruno, estou aqui mais uma vez pra tirar uma dúvida. Comecei a acompanhar a série semana passada e no momento estou na aula 7. Vi que foi preciso atualizar o repositório por meio do github, mas não to conseguindo clonar para meu PC. Seria porque quando baixei os arquivos (semana passada), já estava atualizado ? 
Segue a mensagem que aparece: Permission denied ( publickey). Fatal: Could not read from remote repository. 

Desde já, agradeço.

**Comment by brunosantoshx** [comment]
Respondi na outra issue :)
