### ISSUE TITLE
Problema com hospedagem 

### ISSUE THREAD

**Issue by rlcosta** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#36]
Bom dia, estou com o seguinte problema quando upei os arquivos da aula no servidor da hostinger
"Warning: set_time_limit() has been disabled for security reasons in /home/u942981625/public_html/index.php on line 5"
Gostaria de saber se tem algum jeito de resolver, pois quando retiro a linha de código do arquivo a página não carrega

**Comment by brunosantoshx** [comment]
Olá @rlcosta, como vai?

O que parece é que esta função foi desativada nesta hospedagem e a sua remoção do arquivo `index.php` não deveria comprometer o funcionamento de forma alguma. Ative a exibição de erros para verificar se outras funções também não foram desabilitadas e até mesmo algum outro erro esteja ocorrendo.

Forte abraço e sucesso sempre!
