### ISSUE TITLE
Aula 14 - Menus

### ISSUE THREAD

**Issue by Japy88** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#38]
Boas Bruno,

Tenho dois problemas em relação à barra de menu.

1 - Se quiser pôr a mesma barra de menu em diferentes níveis de usuários tenho que replicá-la para todos? É que tentei acrescentar mais do que um usuário no final e não dá.

$configs->env->development->menu->setMenus([
		'/phone' => '%baseURI%/calls',
		'/envelope' => '%baseURI%/emailcaixaentrada',
		'/folder-open' => '%baseURI%/visualizar',
		'/plus' => '%baseURI%/registo',
		'/user' => [
			'Perfil/user' => '%baseURI%/Perfil',
			'Conta/cog' => '%baseURI%/Conta',
			'Sair/off' => '%baseURI%/login/Sair',
			]
		],'user'**,'administrador'**);/* Assim não me funciona e tive que duplicar */

2 - Como é que posso chamar o nome do utilizador para a barra de menu? Tentei aplicar diretamente a função para chamar mas não chama. 

$configs->env->development->menu->setMenus([
		'**<?php echo $view_user->name; ?>**/user' => [
			'Perfil/user' => '%baseURI%/Perfil',
                        'Sair/off' => '%baseURI%/login/Sair',
                        ]
		],'user'); /* Não permite chamar nem o nome nem imagem*/

Abraço

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

A sacada do MenuHelper é criar um menu diferente para cada nível de acesso e, por isso, não existe esta opção de utilizar um mesmo menu para dois níveis diferentes. Se você pretende utilizar um comum entre usuários pode criar um menu para um nível fictício, ou seja, você coloca 'duplicar' (nome qualquer) ao invés de 'user' ou 'administrator' e na hora de carregar o helper é só escrever 'duplicar' ao invés de pegar a role do usuário. Isto porque não existe a necessidade de validar nível de acesso já que os menus são os mesmos e não optei por usar o menu neutro porque você pode querer utilizar nas páginas públicas.

E sobre resgatar o nome de usuário: Isto só será possível com JS já que no arquivo de configuração não existe acesso aos models, isto é, não existe conexão alguma com o banco de dados. Você pode colocar um coringa e substituir com JS.

Forte abraço e sucesso sempre!
