### ISSUE TITLE
PHPActiveRecord

### ISSUE THREAD

**Issue by junio-gon** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#39]
Boa noite,

em qual arquivo, e emque parte eu insiro as configurações e string de conexão do phpactiverecord? Assisti a série, mas qdo insiro o código no index dapasta sistema sempre dá erro!

Obrigado

**Comment by brunosantoshx** [comment]
Olá @junio-gon, como vai?

Você sempre vai passar estas informações no `app/config.php`.

Forte abraço e sucesso sempre!
