### ISSUE TITLE
Automatizar redirectCheck

### ISSUE THREAD

**Issue by ghost** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#4]
Conforme mostrado na [última aula](https://www.youtube.com/watch?v=TymsCJKdSSg), caso eu queira proteger uma página e forçar o usuário a ir á uma página de login, ou outra página, seria necessário usar este bloco de código:

```php
$this->load(
    'Services\Auth',
    $configs->auth->url_after_login,
    $configs->auth->url_after_logout,
    TRUE
 );
            
$this->auth->redirectCheck(TRUE);
```

Há alguma maneira de se automatizar isto? Digo, criar alguma rotina para que apenas:
```php
$this->auth->redirectCheck(TRUE) 
```
 faça este serviço?

PS: Grato pela referência a minha contribuição no vídeo da última aula, espero continuar contribuindo muito para o HXPHP :computer:

**Comment by brunosantoshx** [comment]
Olá @carusogabriel, como vai?

É possível, porém, como padrão, não é recomendado. Vou explicar:

Se eu injetar o serviço `Auth` na classe mestre `Controller` e passar as devidas configurações, conseguirei o resultado que você citou acima, porém, o serviço de autenticação não é de uso frequente e imprescindível, ou seja, na verdade é algo esporádico, portanto não posso injetá-lo por padrão, visto que ele não tem tanta relevância.

A ideia é bem interessante e podemos pensar em algo como, por exemplo: 

Poderíamos criar algo nas configurações de forma que pudéssemos setar um objeto para ser injetado, suas configurações e em quais controllers seria injetado. O que acha?

**Comment by brunosantoshx** [comment]
Imagine:
```php
$configs->controllers->load(
     array(
        'CadastroController',
        'LoginController'
     ),
     'Services\Auth', 
     $config1,
     $config2,
     $config3
);
```
