### ISSUE TITLE
Erro - Autenticação

### ISSUE THREAD

**Issue by lucas-martins** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#40]
Boa tarde, 

Estou tendo problemas no momento da autenticação do usuário, verifiquei os arquivos apresentados na mensagem de erro porém não consegui encontrar o erro. Segue o erro:

Fatal error: Uncaught exception 'Exception' with message 'O bloco <'alerts'> nao foi encontrado no template <'C:\xampp\htdocs\sistema\src\HXPHP\System\Modules\Messages\templates\auth.json'>.' in C:\xampp\htdocs\sistema\src\HXPHP\System\Modules\Messages\Messages.php:87 Stack trace: #0 C:\xampp\htdocs\sistema\src\HXPHP\System\Modules\Messages\Messages.php(69): HXPHP\System\Modules\Messages\Messages->__get('alerts') #1 C:\xampp\htdocs\sistema\app\controllers\LoginController.php(34): HXPHP\System\Modules\Messages\Messages->__call('getByCode', Array) #2 C:\xampp\htdocs\sistema\app\controllers\LoginController.php(34): HXPHP\System\Modules\Messages\Messages->getByCode('usuario-inexist...') #3 [internal function]: LoginController->logarAction() #4 C:\xampp\htdocs\sistema\src\HXPHP\System\App.php(103): call_user_func_array(Array, Array) #5 C:\xampp\htdocs\sistema\index.php(31): HXPHP\System\App->run() #6 {main} thrown in C:\xampp\htdocs\sistema\src\HXPHP\System\Modules\Messages\Messages.php on line 87

**Comment by rogereicchert** [comment]
Boa noite @lucas-martins , 

tu ja verificastes o metodo logarAction() se nao esqueceu de algum argumento? Pelo que me parece so esta dando erro nesse metodo, alguma pendencia que nao colocou, algum array a mais ou a menos... Se possivel nos traga o metodo para ca para darmos uma analisada. 

(desculpa a falta de acentos, teclado ruim).

Abraço

**Comment by brunosantoshx** [comment]
Olá @lucas-martins, como vai?

Acesse esta ferramenta (http://jsonlint.com/); cole o conteúdo do arquivo `C:\xampp\htdocs\sistema\src\HXPHP\System\Modules\Messages\templates\auth.json`, e; depois clique em `validate`.

O erro apresentado é comum quando o JSON do template está corrompido. Isso acontece geralmente quando você pula linhas ou tenta indentar o conteúdo. 

Acredito que com isto o problema seja 100% resolvido.

Forte abraço e sucesso sempre!
