### ISSUE TITLE
href button

### ISSUE THREAD

**Issue by Japy88** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#43]
Boas Bruno,

No seguimento da última aula você mostrou como criar forms com a nova dependência e eu comecei a atualizar os formulários de login, registo, etc não consigo criar o botão para redirecionar página.

Form::Button(
                'Esqueci-me da senha',
                'submit', [
                  'href' => '<?php echo BASE; ?>recuperar/">'
                ]
              );

Abraço!

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

A tag `button` não contém o atributo `href`, isto é, o redirecionamento, no geral, ocorre para a URL especificada no `action` do `form`quando é um `submit button`. 

Resumindo, a dependência não pode ser utilizada porque o link não é um campo/botão de formulário e sim uma tag específica `a` que é só você inserir normalmente o HTML onde deseja exibir.

Forte abraço e sucesso sempre!
