### ISSUE TITLE
upload/atualizar imagem

### ISSUE THREAD

**Issue by Japy88** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#45]
Boas Bruno,

Sei que a aula ainda não foi para o ar, mas tentei correr o código e embora a imagem tenha upado, apareceu este erro:

Warning: unlink(C:\xampp\htdocs\Iurisdb\\public\uploads\users\24\): Permission denied in C:\xampp\htdocs\Iurisdb\app\controllers\PerfilController.php on line 60

24 é o id do user que utilizei para atualizar.

Forte abraço!

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

Está faltando a imagem em si para ser deletada. Perceba que o que está sendo passado para a função unlink é um diretório. É preciso adicionar a coluna no banco de dados também e você poderá acompanhar tudo em detalhes na aula que já foi publicada. 

Forte abraço e sucesso sempre!

**Comment by Japy88** [comment]
Valeu! Já vi a aula e vi isso explicado. Como a aula não tá no seguimento da lista na página do youtube eu não tinha visto. Mas já encontrei e confirmei.

Brigado e muitos parabéns pelas aulas!
