### ISSUE TITLE
Sugestão de nova funcionaliodade

### ISSUE THREAD

**Issue by CelaumMm** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#47]
Boa tarde,
A serie criando sistema de cadastro e login é muito bom, uma sugestão de novo modulo que poderia substituir o Messages ou criar um novo chamado exe: notifications

[https://github.com/CodeSeven/toastr](https://github.com/CodeSeven/toastr)

**Comment by rogereicchert** [comment]
Eu gostei dessa funcionalidade, vou colocar aqui numa pasta de teste e verificar se realmente fica bom. Depois venho aqui e digo se poderia ser util ou nao. 

Abraço

**Comment by brunosantoshx** [comment]
Olá @CelaumMm, como vai?

Obrigado pela sugestão. Realmente pode ser um módulo bem interessante. Vou realizar alguns testes e pretendo adicionar este recurso em uma nova versão futuramente.

Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications (https://github.com/CodeSeven/toastr)](https://trello.com/c/oiDrPj58/130-notifications-https-github-com-codeseven-toastr)
