### ISSUE TITLE
Cadastro Bug mesmo com verificaçao de dados

### ISSUE THREAD

**Issue by rogereicchert** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#48]
Primeiramente desculpe pela falta de acentuaçao, pois meu teclado esta com problemas. 

Vamos a questao. Na tela de cadastro, esta todo configurado de acordo com tudo que foi demonstrado e explicado, refiz umas 3 vezes antes de vir ate aqui, no codigo esta configurado para verificar login e email certo? Porem fazendo testes constatei que, quando eu cadastro um e-mail ja existente com um usuario diferente, ele cadastra do mesmo jeito, ou se eu cadastro um e-mail diferente com um usuario ja existente no banco, cadastra tambem. Somente mostra o erro: "Ja existe um usuario com esse e-mail e/ou nome de usuario cadastrado" quando somente o usuario e email forem iguais a um cadastro ja efetuado. 

Agradeço desde ja.

**Comment by brunosantoshx** [comment]
Olá @rogereicchert, como vai?

Isto foi ajustado durante a série nas próximas aulas. A primeira validação que eu usei utilizava a lógica AND e só acusava quando os dois eram iguais, exatamente como você mencionou. Mas, depois alterei para OR. É só continuar assistindo ou conferir como ficou diretamente no repositório (app/models/User.php).

Forte abraço e sucesso sempre!

**Comment by rogereicchert** [comment]
Ahh sim, muito obrigado. 

(ainda com problema de acentuaçao no teclado).

E que nao gosto de avançar, gosto de ver a aula, e depois fazer os codigos, primeiro entender e depois faze-los. Mas continuarei acompanhando. Muito obrigado mesmo. E quero dizer que aqui realmente e muito util, gostei demais do git hub. Valeu a dica.

**Comment by FRANCISCORICARDO1910** [comment]
Boa noite bruno,


Não sei se e por aqui que deve perguntar, mas estou acompanhando suas aulas de hxphp criando sistema de login e gostei bastante estou ate desenvolvendo um sistema com ele, mais estou com dificuldade em atualizar um usuario.


Criei uma lista, chamei os usuarios igual vc fez na aula, criei os link para editar e deletar, passados os dados para o controller mais na hora que passo o post do formulario edita e tento atualizar os dados na um erro.


ja usei


save(), quanto o update_attributes(), os dois dão erro .


Poderia me ajudar()


________________________________
De: Bruno Campos Santos <notifications@github.com>
Enviado: quinta-feira, 15 de setembro de 2016 16:13
Para: brunosantoshx/serie-criando-sistema-de-cadastro-e-login
Assunto: Re: [brunosantoshx/serie-criando-sistema-de-cadastro-e-login] Cadastro Bug mesmo com verificaçao de dados (#48)


Closed #48<https://github.com/brunosantoshx/serie-criando-sistema-de-cadastro-e-login/issues/48>.

-

**Comment by brunosantoshx** [comment]
Olá @FRANCISCORICARDO1910, como vai?

Pra eu te ajudar preciso saber que erro está sendo retornado. Copie e cole o erro completo em uma nova issue.

Fico no aguardo.
Forte abraço e sucesso sempre!
