### ISSUE TITLE
Erro ao cadastrar usuário

### ISSUE THREAD

**Issue by fabianofs** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#49]
Olá Bruno, tudo bem?
Estou tendo um erro ao cadastrar o usuário. Fiz a atualização do HXPHP, quando voltei a continuar com o projeto, me aparece esse erro, 
"Ops! Não foi possível efetuar seu cadastro. 
Verifique os erros abaixo:

A role user não existe. Contate o administrador".
Se você tem algum parecer a esse erro, fico grato.

Atenciosamente

Fábio Souza

**Comment by Japy88** [comment]
Antes de mais quero agradecer ao Bruno pela série que está muito boa e que é o melhor professor que vi a dar aula de php em pt. na net. Espero que continue o bom trabalho e que não fique por aqui.

Quanto ao Fabianofs, se não me engano tem que ir à base de dados e na tabela "roles" tem que criar/inserir duas rows, uma com o "id = 1 e a role = administrator (em inglês)"  e outra com o "id = 2 e o role user". Pode tirar dúvidas nas aulas iniciais, a 4 se não me engano.

**Comment by rogereicchert** [comment]
Exatamente, tem que ir ao banco de dados e cadastrar duas roles: ID = 1 Administrator e ID = 2 User.
Aconteceu comigo esse mesmo problema, quando nao cadastrei na tabela "roles", Espero termos te ajudado.

Sim e concordo tambem que e o melhor professor de programaçao que ja tive.

**Comment by brunosantoshx** [comment]
Olá @Japy88 e @rogereicchert, como vão? Antes de qualquer coisa, muito obrigado pelo feedback e tenham certeza que são comentários assim que sempre me fizeram e farão produzir cada vez mais conteúdos de qualidade para vocês. Vocês são demais! 

E podem ficar sossegados que teremos muitas novidades no canal ainda este ano! Estamos só começando hehehe.

E @fabianofs, nem precisei lhe responder porque a comunidade já fez isto por mim. Eles estão corretíssimos e representaram compartilhando seu tempo e conhecimento.

Forte abraço e sucesso sempre!

**Comment by rogereicchert** [comment]
@brunosantoshx  obrigado, quando temos que reconhecer e elogiar pelo otimo trabalho, claro que criticas virao, ja estou preparando uma :p. Mas sempre e no sentido construtivo. Mas no demais Obrigado mesmo. Esta ajudando demais nesse quesito MVC que eu era bem fraco.

@fabianofs nos de retorno se conseguiu resolver teu problema por gentileza.
