### ISSUE TITLE
Koala APP

### ISSUE THREAD

**Issue by capiche2234** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#5]
Cara estou vendo aqui o Koala APP mas o que eu faço como vou configurar o Scss na pasta projeto do seu site??﻿ ME AJUDA AI.

**Comment by carusogabriel** [comment]
Olá @capiche2234 

Se a sua dúvida é referente a estrutura do projeto para compilação do `.scss`, você pode criar uma pasta no `/public/scss/` e compilar para `/public/css/`

**Comment by capiche2234** [comment]
como faz isso
eu não sei

**Comment by capiche2234** [comment]
cara quando eu salvo o projeto scss ele da esse erro:  Errno::ENOENT: No such file or directory - C:\Users\Capiche2234\Desktop\Como criar um site profissional passo a passo - C�pia\projeto\scss\style.scss
  Use --trace for backtrace.

**Comment by capiche2234** [comment]
pode me ajudar???

**Comment by carusogabriel** [comment]
Você tem que conferir as pastas, para onde está indo os arquivos `.scss` compilados!
Neste caso parece que você indicou `\projeto\scss` e não `projeto\public\scss`

**Comment by capiche2234** [comment]
COMO ASSIM
?

**Comment by capiche2234** [comment]
NÃO VAI MUDAR NADA

**Comment by capiche2234** [comment]
C:\Users\Capiche2234\Desktop\Como criar um site profissional passo a passo - C�pia\projeto\scss\style.scss
Use --trace for backtrace.

**Comment by capiche2234** [comment]
EU QUERO TIRAR ISSO

**Comment by capiche2234** [comment]
PODE ME DIZER QUAL É O PROBLEMA?

**Comment by capiche2234** [comment]
EU QUERO CRIAR MEU SITE!

**Comment by capiche2234** [comment]
ME AJDUA AI

**Comment by capiche2234** [comment]
amanha se me ajuda,vou dormir

**Comment by capiche2234** [comment]
Me ajuda ai ate agira se nao falo nada

**Comment by carusogabriel** [comment]
Olá @capiche2234
Peço para que você procure sobre o assunto na internet, a parte de `issues` em um repositório é para dúvidas do mesmo!
