### ISSUE TITLE
Erro Fatal Aula 4

### ISSUE THREAD

**Issue by melquilegend** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#50]
Ola Bruno pode me audar eu tenho esse erro aula 4:Fatal error: Uncaught exception 'ActiveRecord\UndefinedPropertyException' with message 'Undefined property: User->password in C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php on line 432' in C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php on line 1250
( ! ) ActiveRecord\UndefinedPropertyException: Undefined property: User->password in C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php on line 432 in C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php on line 1250
Call Stack

**Comment by rogereicchert** [comment]
Ola amigo, nao sou o bruno, mas poderei te ajudar, me passa o codigo onde esta User->password para eu dar uma olhada.

**Comment by melquilegend** [comment]
<?php

class CadastroController extends \HXPHP\System\Controller
{
	public function cadastrarAction()
	{
		$this->view->setFile('index');
		$this->request->setCustomFilters(array(
			'email'=>FILTER_VALIDATE_EMAIL
			));
		$cadastrarUsuaio = User::cadastrar($this->request->post());
		
	}


}

**Comment by melquilegend** [comment]
<img width="683" alt="pm" src="https://cloud.githubusercontent.com/assets/19785948/18565378/d54e6eb6-7b8f-11e6-9534-87934e625763.png">
![untitled](https://cloud.githubusercontent.com/assets/19785948/18565389/df84e806-7b8f-11e6-8697-902e953a2bec.jpg)

**Comment by melquilegend** [comment]
<img width="683" alt="untitledff" src="https://cloud.githubusercontent.com/assets/19785948/18565493/3a9c82d0-7b90-11e6-83bc-23d06f851435.png">
<img width="683" alt="pm" src="https://cloud.githubusercontent.com/assets/19785948/18565494/3aad8ee0-7b90-11e6-98b8-676041ce2651.png">

**Comment by melquilegend** [comment]
quando clico cadastrar vem este erro na imagem de baixo

**Comment by brunosantoshx** [comment]
Olá @melquilegend e @rogereicchert, como vão?

Este tipo de erro é padrão, isto é, quando o PHP Activerecord acusa `Undefined property' é porque você está definindo ou solicitando dados de uma coluna não existente na tabela do respectivo model. Resumindo, aposto minhas fichas que na tabela `users` a coluna `password` não existe ou está nomeada de forma diferente.

Forte abraço e sucesso sempre!

**Comment by rogereicchert** [comment]
Exato, eu iria dizer isso analisando o codigo, porem o bruno chegou primeiro hahaha. Verifica la na tabela se esta diferente ou existe :p Abraço a ambos.
