### ISSUE TITLE
Dúvida sobre o campo Salt no banco de dados

### ISSUE THREAD

**Issue by rogereicchert** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#51]
Creio que seja a duvida mais facil. haha
Olá boa noite, venho mais uma vez aqui incomodar :p, Mas seguinte, como o campo salt no banco de dados é gerado? Porque eu vi que todos os campos são referenciados no código, mas o campo salt é o único que não aparece como campo... por exemplo: $salt = alguma_coisa_código_aqui.. Isso realmente não entendi até agora. Obrigado desde já.

**Comment by Lesnock** [comment]
@rogereicchert Na verdade o salt não é gerado no banco de dados, ele é gerado no PHP. 
Quando você utiliza a função `\HXPHP\System\Tools\HashHX($senha)`, ele retorna um array com dois valores: 

1. A senha criptografada
2. O salt, que é a chave de criptografia

Aí sim você pode seguir a diante e registrá-los no banco de dados.

Segue um exemplo para você entender melhor:

Captura a senha digitada pelo usuário:
**`$senha = $this->request->post('senha'); `**

A linha de código abaixo é responsável por criptografar a senha:
**`$senha_criptografada = \HXPHP\System\Tools\HashHX($senha);`**

Observe agora que a variável $senha_criptografada é um array contendo a senha criptografada e o salt utilizado na criptografia

Agora basta registrar no banco (supondo que a tabela User só tenha o campo de senha e salt):
**`User::create($senha_criptografada); `**

**Comment by brunosantoshx** [comment]
Olá @rogereicchert e @Lesnock, como vão?

É exatamente isto que o @Lesnock respondeu. A única observação é que o hashHX é um método estático, portanto o correto seria:

```php
$senha_criptografada = \HXPHP\System\Tools::hashHX($post['password']);
```

Mas todo o funcionamento explicado, em detalhes, pelo @Lesnock está corretíssimo e preciso.

É isso aí galera! Um ajudando o outro sempre que vamos crescendo cada vez mais!
Parabéns pela resposta @Lesnock 

Forte abraço e sucesso sempre!
