### ISSUE TITLE
Erro de propriedade não definida

### ISSUE THREAD

**Issue by thiagomnobre** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#52]
bom dia estou com o seguinte erro e não estou conseguindo encontrar uma solução.

var_dump abaixo
array(6) { ["name"]=> string(27) "Telos Soluções Ambientais" ["CNPJ"]=> string(18) "11.111.111\0001-11" ["responsavel"]=> string(7) "Marcelo" ["contato"]=> string(13) "19 11111-1111" ["email"]=> string(20) "marcelo@telos.com.br" ["tipo_empresa_id"]=> int(1) } 

erro
Fatal error: Uncaught ActiveRecord\UndefinedPropertyException: Undefined property: User->CNPJ in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php on line 432 Undefined property: User->responsavel in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php on line 432 Undefined property: User->contato in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php on line 432 Undefined property: User->tipo_empresa_id in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php on line 432 in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php:1250 Stack trace: #0 /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php(273): ActiveRecord\Model->set_attributes_via_mass_assignment(Array, true) #1 /www/telos/src/HXPHP/System/Model.php(16): ActiveRecord\Model->__c in /www/telos/vendor/php-activerecord/php-activerecord/lib/Model.php on line 1250

**Comment by brunosantoshx** [comment]
Olá @thiagomnobre, como vai?

O PHP Activerecord converte os nomes de todas as colunas para lowercase, isto é, o certo seria `cnpj` em vez de `CNPJ`. 

Alterando o nome da propriedade já resolverá o problema.

Forte abraço e sucesso sempre!
