### ISSUE TITLE
Erro ao conferir Password para Login

### ISSUE THREAD

**Issue by KDuh** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#53]
Muito boa noite! 
Estava acompanhando as aulas e quando cheguei a Aula 8 e fui fazer a validação de Login, ou seja, conferir o password com o que consta no banco de dados ele me retornou um erro. 

array(1) { ["username"]=> string(14) "Carlos Eduardo" } 
Notice: Undefined index: password in /var/www/html/sistema/app/models/User.php on line 68
array(2) { ["salt"]=> string(128) "e6847522cdb2e07111727ece88d73ce2c4b1d892153264fafc703450841a56176be7e50f99ab83ae106e991f7a69d0d84831819cd9b6728eabb605ae3ed4a2ea" ["password"]=> string(128) "4ff36e4f46e060c5c25b7a9e0491c48e7f4ca2d655f841a170efe25081045ca48ba350f0aeb0504c8e80e893616a0ef49735feb49d4664a7ad6c078acf8a4f47" }

Analisando esse erro eu pude constatar que o "salt" está correto, porém o password gerado pelo Hash está errado, ou seja, não descriptografado ou algo assim.

E o meu código está igual ao da Aula 8;

public static function login(array $post){
	$user = self::find_by_username($post['username']);

	if(!is_null($user)){

		$password = \HXPHP\System\Tools::hashHX($post['password'], $user->salt);

		if(LoginAttempt::ExistemTentativas($user->id)){
			if($password['password'] === $user->password){
				var_dump('logado');
				LoginAttempt::LimparTentativas($user->id);
			}else{
				LoginAttempt::RegistrarTentativa($user->id);
			}
		}
	}
}

O que poderia ser erro? Eu errei em algum lugar?

**Comment by brunosantoshx** [comment]
Olá @KDuh, como vai?

Desculpe a demora em lhe responder. Cheguei há pouco de viagem e estou retomando tudo conforme consigo.

Acredito que o problema esteja no seu HTML. Verifique se o INPUT responsável pela senha está com o name setado como `password`.

Fico no aguardo.
Forte abraço e sucesso sempre!
