### ISSUE TITLE
Problema ao autenticar usuário

### ISSUE THREAD

**Issue by luishmdasilva10** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#54]
Bruno, boa tarde.

Estou na aula 7 e estou tendo este problema.
Quando depois de preencher o cadastro o sistema deveria enviar para a tela do Home porém não envia.

Já olhei o vídeo varias vezes, já baixei os arquivos e comparei porem não estou conseguindo achar o problema. Será que poderia me ajudar.

Apareci a mensagem em anexo:
![capturar](https://cloud.githubusercontent.com/assets/22282185/19221939/4ed71328-8e23-11e6-94e6-0dd87b690339.PNG)

Meu e-mail é: luishmdasilva@gmail.com

**Comment by brunosantoshx** [comment]
Olá @luishmdasilva10, como vai?

Desculpe a demora em lhe responder. Cheguei há pouco de viagem e estou retomando tudo conforme consigo.

Você atualizou o HXPHP? Estamos sempre corrigindo erros e alguns deles foram causados por algumas contribuições que afetaram as condicionais do framework. Acredito que o seu problema possa estar relacionado com isto.

Se mesmo com o HXPHP atualizado o problema persistir, o ideal é que você crie um repositório e envie todos os seus arquivos para que eu possa estudar com mais detalhes.

Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by luishmdasilva10** [comment]
Bruno, boa tarde.

O HXPHP já está na última versão.
E o repositório está no Github e chamado "sistema".

https://github.com/luishmdasilva10/sistema

Lá está no commit da vez que deu o erro. Até parei de mexer pois não
consegui achar o erro.

Me ajuda por favor para que eu possa continuar, pls..

Att,
Luis Henrique Morais.

Em 17 de out de 2016 22:33, "Bruno Campos Santos" <notifications@github.com>
escreveu:

**Comment by brunosantoshx** [comment]
Olá @luishmdasilva10, como vai?

Acredito que tenha ocorrido algum problema durante a atualização do HXPHP porque os arquivos não batem. Veja:

https://github.com/luishmdasilva10/sistema/blob/master/src/HXPHP/System/Services/Auth/Auth.php

https://github.com/brunosantoshx/hxphp/blob/master/src/HXPHP/System/Services/Auth/Auth.php

Veja o método construtor para se ter uma ideia da diferença entre ambos os arquivos. Recomendo que você delete totalmente a pasta `src` e substitua pela do repositório oficial do HXPHP.

Isto resolverá seus problemas.
Forte abraço e sucesso sempre!
