### ISSUE TITLE
Problema para hospedar Sistemas com Framework - HXPHP

### ISSUE THREAD

**Issue by StarkilerR** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#55]
Bruno Santos, amei o HXPHP, ele é simples, completo e versátil, atende a todas as minhas necessidades para criar um sistema para meu TCC, e á cada vídeo aula, tinha mais certeza que se encaixaria como uma luva para mim, porem chegou a a aula #10, aula sobre hospedagem e simplesmente fui "forçado" e pausar o curso, pois não consigo Hospedar o sistema criado durante as aulas em NENHUM serviço de hospedagem...

Dos diversos serviços de hospedagem os que chegaram mais perto de funcionar foram:

**hostinger**
Esse foi o que chegou mais perto de funcionar, porem por alguma configuração do servidor, ou incompatibilidade com a aplicação, logo na tela de apresentação do framework já apresenta o seguinte erro:

`Warning: set_time_limit() has been disabled for security reasons in /home/u761393804/public_html/index.php on line 5`

Dei uma olhada e já teve pessoas com o mesmo problema( #36 ), porem não teve solução confirmada...
Mas os problemas não acabam por ai, quando e necessário fazer uma conexão com o Banco de Dados ( no caso o Login ) a aplicação não conseguem, retornando o erro:
`Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)' in /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Connection.php:181 Stack trace: #0 /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Connection.php(118): 

`ActiveRecord\Connection::parse_connection_url('mysql://u761393...') #1 /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/ConnectionManager.php(33): ActiveRecord\Connection::instance('mysql://u761393...') #2 /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Table.php(114): ActiveRecord\ConnectionManager::get_connection(NULL) #3 /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Table.php(90): ActiveRecord\Table->reestablish_connection(false) #4 /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Table.php(71): A in /home/u761393804/public_html/vendor/php-activerecord/php-activerecord/lib/Connection.php on line 181`

Depois de diversas pesquisas e tentativas para corrigir esses erros mas sem sucesso, resolvi procurar outro serviço de hospedagem, e por gostar tanto do HXPHP resolvi assinar uma hospedagem paga, que por lógica, ofereceria uma qualidade maior, que talvez assim solucionaria meu erro , Host escolhido foi a **GoDaddy**, e o resultado foi pior que o anterior, pois nem mesmo a tela de apresentação do HXPHP ele conseguiu retornar. A unica coisa que retorna, e a tela error404 configurada, porem a mesma sem nenhum tipo de formatação ou CSS empregado...

Pelo que parece, você também tem hospedagem pela GoDaddy, então talvez senha mais fácil me apontar onde estou errando. Estou precisando urgentemente de uma luz nesse problema que me encontro... Pois a unica solução que encontrei foi trocar de Framework, o que não garante em nada que resolvera essas incompatibilidades...

Segue o endereço onde estão hospedados minha aplicação:
**hosteger:** http://tcc-sistema-orion.esy.es/
**GoDaddy:** http://tcc-sistema-orion.xyz/sistema/

**Comment by brunosantoshx** [comment]
Olá @StarkilerR, como vai?

Desculpe a demora em lhe responder. Cheguei há pouco de viagem e estou retomando tudo conforme consigo.

Desde já, gostaria de ressaltar a minha felicidade ao ler seu comentário sobre a aplicação do HXPHP em seu TCC e acrescento que gostaria de mais detalhes, se possível, sobre o projeto e até mesmo o resultado final (link, vídeo ou algo que apresente). Se precisar de ajuda é só postar por aqui que faremos o possível para lhe ajudar.

**Sobre hospedagem:**

+ Para funcionar de imediato é necessário que seja Linux, pois em hospedagens Windows o .htaccess não surte efeito, portanto requer uma adaptação;
+ O erro reportado pela Hostinger é o seguinte: O HXPHP tem uma configuração que altera o tempo limite do servidor para execução de scripts, porém esta hospedagem, por ser gratuita, não permite tal funcionalidade e reporta este erro. A solução é remover o código apontado no próprio log de erro: `/home/u761393804/public_html/index.php on line 5`;
+ Já na GoDaddy o erro parece ocorrer na configuração (app/config.php). Acredito que a `baseURI` esteja definida como `/`, porém o framework encontra-se instalado em uma subpasta, portanto o certo seria `/sistema/`. Também é possível que o mesmo erro esteja no arquivo `.htaccess` que precisa estar com o mesmo valor de base da URL.

Fico no aguardo dos seus comentários.
Forte abraço e sucesso sempre!

**Comment by StarkilerR** [comment]
Olá @brunosantoshx , muito obrigado por entrar em contado e pelas sugestões. Realmente tinha um pequeno erro no `baseURI` do `app/config`, que ao arrumar, o HXPHP subiu tranquilamente. Porem logo em seguida já constatei outro problema, a pagina `/sistema/cadastro/` não é carregada, ela não retornar nem o `error404` como também nenhum tipo de conteúdo, a pagina fica totalmente em branco, como se o caminho fosse encontrado mas não tivesse nenhum tipo de conteúdo para ser exibido. Como não está acontecendo com a pagina `/sistema/login/`, acreditei que se tratava de mais um erro de sintaxe, porem quando eu rodei na local ( servidor e local estão na mesma versão de arquivos ) a pagina carrega normalmente como a login, apenas no servidor o problema ocorre. Eu cheguei e desfazer o subdomínio e deletar todos os arquivos da aplicação e reinvialos, porém o problema persiste...

Bom, pelo menos um dor de cabeça já foi resolvida e posso realizar testes com os usuários que já estão cadastrados ate encontrar algum jeito de resolver isso. Agradeço novamente por entrar em contato e pela preocupação. Forte abraço e sucesso Bruno !

**Comment by brunosantoshx** [comment]
Olá @StarkilerR, como vai?

Maravilha! Fico feliz que o problema principal já foi corrigido.

O que deve estar ocorrendo é um erro que não está sendo apresentado por conta de alguma configuração que desabilita a exibição de erros, portanto confira se existe um arquivo `error_log` na raiz da sua hospedagem.

O que ocorre é que o PHP da sua máquina possivelmente está configurado de forma diferente em comparação com o PHP da hospedagem. Existem alguns erros que não são apontados na sua máquina, porém não são tolerados no servidor e isto é algo bem comum. Inclusive, tive que adaptar um sistema ontem por conta disto.

Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by EmersonRomao** [comment]
Olá @brunosantoshx, como vai?

Desde já quero parabenizá-lo pelo HXPHP Framework, comecei a utilizá-lo neste momento, porém já assiti no Youtube todas as aulas que vc ministrou sobre o assunto, estou colocando na prática. Neste momento, sigo com o mesmo problema do @StarkilerR, ao executar meu cadastro com o método create($post) recebo a mesma mensagem discutida aqui neste post:

Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)' in C:\wamp64\www\cmw\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 182
--

Nota: Estou utilizando o PostgreSql, e minha setConnectionData está configurada dessa forma:

$this->setConnectionData([
            'host' => 'localhost',
            'user' => 'cmwadmin',
            'password' => 'Utilizo senha com caracteres maiúsculo/minúsculo e números ',
            'dbname' => 'cmwdb',
            'charset' => 'utf8'
        ]);

Por favor, poderia me ajudar?

Fico no aguardo.
Abraço e sucesso!

**Comment by flemej** [comment]
Olá, Emerson!
Já tentou substituir a palavra "localhost" por "127.0.0.1"?

**Comment by EmersonRomao** [comment]
Olá @flemej,

Obrigado, sim já tentei! Continua com a mesma mensagem.
Inclusive no arquivo que determina as variáveis para o ambiente de desenvolvimento, estão os dois endereços para identificar o server, veja:

$this->servers = array(
            'localhost',
            '127.0.0.1'
        );

Abraço.

**Comment by Davidsonc** [comment]
Boa tarde, será que alguem tem um crud ai que possa me passar para eu seguir ? tenho estudado o hxphp a cerca de uma semana e estou empacado no quesito de views mais elaboradas, com window.open por exemplo, sinto que terei que passar a usar modais, ate consigo, mas gostaria de fazer isso da maneira correta de uma forma elegante, cansei de lutar com html jscript crus na mao grande... davidsonc@gmail.com entrem em contato! ah.. tb estou com o problema na classe forms adoraria poder programar formulários html dentro do php do lado do servidor, mas ainda estou fazendo por html. ja reinstalei o hxphp e continua na mesma ao clicar no editar... galera nao é preguiça nem burrice, tem uns 15 dias que venho lutando e qualquer ajuda sera de grande valia. desde já grato, Davidson Campos
