### ISSUE TITLE
Login com Google

### ISSUE THREAD

**Issue by renanteixeira** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#59]
Boa tarde,

É possível implantar o método de autenticação via Google nesta ferramenta? Estou implantando um sistema global aqui na empresa e para poder utilizar por completo o HXPHP preciso desta funcionalidade.

Abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Olá @renanteixeira, como vai?

Sim! E não somente Google como todas as demais redes sociais. Um exemplo de aplicação:
https://github.com/google/google-api-php-client

Espero ter ajudado.
Forte abraço e sucesso sempre!
