### ISSUE TITLE
$DOMAIN

### ISSUE THREAD

**Issue by jhonleandres** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#6]
Qual a melhor forma de implementa o seguinte senário 

http://localhost/{$DOMAIN}/CONTROLLER/

esse campo $DOMAIN seria pesquisado no banco de dados se existe caso exista sera redirecionado para a pagina de login com sua respectivas configurações exemplo "Banco de dados, logo e etc."

**Comment by brunosantoshx** [comment]
Olá @jhonleandres, como vai?

Infelizmente, o HXPHP ainda não conta com recursos que possibilitem implementar tal funcionalidade em um sistema. 

Eu já fiz uma versão do HXPHP que exercia exatamente esta função, porém nesta situação foi uma total customização do framework e, não, uma configuração. Pretendo implementar algo dinâmico quanto a isto futuramente.

Forte abraço e sucesso sempre!
