### ISSUE TITLE
Upload e Download por nome de usuário

### ISSUE THREAD

**Issue by EusRique** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#60]
Olá,

como eu faria para que o adm fizesse upload de um arquivo e disponibilizasse para download apenas para um determinado usuário, no caso ele escolheria em uma lista de usuários já cadastrado no sistema.
Quando o usuário fizer o login em sua conta teria uma área onde iria visualizar os arquivos para baixar.

**Comment by brunosantoshx** [comment]
Olá @EusRique, como vai?

Isto é bem simples. É só criar uma tabela que faz o relacionamento com a tabela de uploads e usuários, isto é, user_id e file_id para tabelas files e users.

O administrador envia o arquivo e seleciona o usuário no mesmo formulário. Após o upload, o código irá salvar o link do arquivo na tabela files e criar um registro nesta outra tabela, que poderia ser downloads ou permissions.

Espero ter ajudado.
Forte abraço e sucesso sempre!

**Comment by EusRique** [comment]
Olá Bruno<mailto:notifications@github.com>, desde já agradeço seu retorno e ajuda.


Tentei colocar em prática sua dica mais tive um problema, criei a tabela files e estou conseguindo armazenar todos os atributos do form, só que o atributo image não grava a imagem ou seja aquele código md5, ele grava apenas no diretório local em uma pasta chamada arquivos que criei para armazenar e no bd não grava o caminho, não sei o que pode ser pois segui o mesmo exemplo do tutorial de upload de imagem.


Anexo as imagens, se puder me dar uma luz.

Att.
________________________________
De: Bruno Campos Santos <notifications@github.com>
Enviado: domingo, 13 de novembro de 2016 22:08
Para: brunosantoshx/serie-criando-sistema-de-cadastro-e-login
Cc: Henrique Camargo; Mention
Assunto: Re: [brunosantoshx/serie-criando-sistema-de-cadastro-e-login] Upload e Download por nome de usuário (#60)


Olá @EusRique<https://github.com/EusRique>, como vai?

Isto é bem simples. É só criar uma tabela que faz o relacionamento com a tabela de uploads e usuários, isto é, user_id e file_id para tabelas files e users.

O administrador envia o arquivo e seleciona o usuário no mesmo formulário. Após o upload, o código irá salvar o link do arquivo na tabela files e criar um registro nesta outra tabela, que poderia ser downloads ou permissions.

Espero ter ajudado.
Forte abraço e sucesso sempre!

-

**Comment by EusRique** [comment]
Olá Bruno,


depois de quebrar a cabeça encontrei o problema...haha

Esqueci de salvar o caminho da imagem, não sei se é esta a forma de dizer mas enfim resolvido, e tbm alterei o nome da variavel para cadastrarFile, desde já agradeço.


if (!is_null($cadastrarFile->image)) {
          unlink($dir_path . $cadastrarFile->image);
}

$cadastrarFile->image = $image_name . '.png';



________________________________
De: Henrique . <hiquesc_@hotmail.com>
Enviado: segunda-feira, 21 de novembro de 2016 01:38
Para: brunosantoshx/serie-criando-sistema-de-cadastro-e-login; brunosantoshx/serie-criando-sistema-de-cadastro-e-login; Bruno Campos Santos
Cc: Mention
Assunto: Re: [brunosantoshx/serie-criando-sistema-de-cadastro-e-login] Upload e Download por nome de usuário (#60)


Olá Bruno<mailto:notifications@github.com>, desde já agradeço seu retorno e ajuda.


Tentei colocar em prática sua dica mais tive um problema, criei a tabela files e estou conseguindo armazenar todos os atributos do form, só que o atributo image não grava a imagem ou seja aquele código md5, ele grava apenas no diretório local em uma pasta chamada arquivos que criei para armazenar e no bd não grava o caminho, não sei o que pode ser pois segui o mesmo exemplo do tutorial de upload de imagem.


Anexo as imagens, se puder me dar uma luz.

Att.
________________________________
De: Bruno Campos Santos <notifications@github.com>
Enviado: domingo, 13 de novembro de 2016 22:08
Para: brunosantoshx/serie-criando-sistema-de-cadastro-e-login
Cc: Henrique Camargo; Mention
Assunto: Re: [brunosantoshx/serie-criando-sistema-de-cadastro-e-login] Upload e Download por nome de usuário (#60)


Olá @EusRique<https://github.com/EusRique>, como vai?

Isto é bem simples. É só criar uma tabela que faz o relacionamento com a tabela de uploads e usuários, isto é, user_id e file_id para tabelas files e users.

O administrador envia o arquivo e seleciona o usuário no mesmo formulário. Após o upload, o código irá salvar o link do arquivo na tabela files e criar um registro nesta outra tabela, que poderia ser downloads ou permissions.

Espero ter ajudado.
Forte abraço e sucesso sempre!

-
