### ISSUE TITLE
Gerenciamento de Download 

### ISSUE THREAD

**Issue by EusRique** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#64]
E ai Bruno, td bom?

Estou com uma pequena dificuldade se puder me ajudar, eu adicionei no menu desse sistema uma tela chamada Arquivos onde o adm faz o upload de um documento e escolhe o usuário que deve ter acesso a este documento para que o mesmo faça o Download. Criei uma nova tabela no banco com o nome files com os seguintes atributos: id, arquivo, date e user_id até aqui td certo. O problema é que qualquer usuário que faça o login tem acesso ao documento para fazer o Download e minha ideia é que somente o usuário escolhido pelo adm no momento do cadastro consiga visualizar. Qual a forma correta de se fazer isso?
Meu código HTML está desta forma, já pesquisei e não consegui encontrar nada, desde já agradeço.

  <div class="panel-body">
      <?php 
        echo isset($this->menu) ? $this->menu->getMenu() : '';
        echo (isset($this->alert) ? $this->alert : '');
      ?>
      
      <table class="table">
        <thead>
            <tr>
              <th>ID</th>
              <th>Arquivo</th>
              <th>Data</th>
              <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php 
              if ($view_files) : 
                foreach ($view_files as $file) :
            ?>
            <tr> 
              <td><?php echo $file->id; ?></td>
              <td><?php echo $file->arquivo; ?></td>
              <td><?php echo $file->date; ?><td>
              <td><a href="arquivos/uploads/files/<?php echo $file->arquivo ?>">Download</a></td>
            </tr>      
        <?php 
            endforeach;
          endif;
        ?>
        </tbody>
      </table>
  </div>

**Comment by brunosantoshx** [comment]
Olá @EusRique, tudo bem?

Eu faria da seguinte forma:

+ Criaria uma tabela chamada `files` e outra `files_to_users`;
+ A tabela `files_to_users` teria as foreign keys `file_id` e `user_id`;
+ Usaria as associações do PHP Activerecord para retornar os arquivos que o usuário tem permissão: `$user->files`. Para saber mais: **Exemplo has_many through (many to many)** -> http://www.phpactiverecord.org/projects/main/wiki/Associations.

Espero ter ajudado.
Forte abraço e sucesso sempre!
