### ISSUE TITLE
Alguma dica para utilização de ajax com o framework?

### ISSUE THREAD

**Issue by AdhamWynston** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#65]
Estou em um projeto da faculdade, no qual é solicitado a utilização de Ajax.
Queria algumas dicas! para usar nesse projeto, fazendo a implementação no sistema de cadastro e login com ajax. Obrigado

**Comment by brunosantoshx** [comment]
Olá @AdhamWynston, como vai?

É bem tranquilo o uso de AJAX com HXPHP! O principal detalhe é se certificar que a `action` responsável pelo retorno dos dados (em JSON, por exemplo) não exibirá nenhum código HTML.

Para isso:
- Crie uma pasta chamada `blank` dentro do diretório `views`;
- Crie uma view chamada `blank.phtml` dentro desta pasta, e;
- Configure a `action` com os seguintes parâmetros:

```php
$this->view->setPath('blank')
			->setFile('blank')
			->setTemplate(false);
```
Nesta `action` você irá receber os dados via GET ou POST e retornar um JSON. Você pode definir que o conteúdo será JSON através do seguinte código:

```php
header('Content-Type: application/json');
```

Espero ter ajudado.
Forte abraço e sucesso sempre!
