### ISSUE TITLE
E-mail de redefinição de senha não chega

### ISSUE THREAD

**Issue by enakonieczny** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#66]
Acompanho a série desde o início e estou desenvolvendo o sistema de login no ambiente de produção, porém, na parte de envio do token para o e-mail, simplesmente ele não chega na caixa de entrada ou spam. Já vi e revi os vídeos referentes à essa parte do sistema e não achei nada de anormal, todas as configurações estão corretas, utilizo um email 'noreply@' de nossa hospedagem para envio. Existe alguma configuração de SMTP que passou despercebida por mim?

Obrigado.

**Comment by serpaulo** [comment]
Estou com o mesmo problema... revi os videos ate a aula 12 e nao consegui da mesma forma...

**Comment by brunosantoshx** [comment]
Olá @enakonieczny, tudo bem? O serviço de e-mail apenas utiliza a função `mail()` sem qualquer autenticação, portanto, é bem provável que este problema esteja ocorrendo devido à algum problema na hospedagem. Recomendo testar individualmente o envio de e-mails apenas com a função `mail()` e depois com alguma ferramenta específica como o PHPMailer.

Fico no aguardo dos resultados.
Forte abraço e sucesso sempre!
