### ISSUE TITLE
Paginação de Usuários e Formulário de Pesquisa

### ISSUE THREAD

**Issue by enakonieczny** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#68]
Estou com o sistema pronto, porém, preciso que os resultados obtidos no banco de dados sejam paginados, como posso fazer isso utilizando o PHP Active Records?

Uma outra dúvida é como fazer para criar um formulário de pesquisa dos usuários cadastrados. Não estou conseguindo achar na internet algo que resolva meu problema. Acho que essas duas funcionalidades a mais no sistema fariam toda a diferença. Desde já, muito obrigado!

**Comment by enakonieczny** [comment]
Uma outra dúvida é como fazer para criar um formulário de pesquisa dos usuários cadastrados. Não estou conseguindo achar na internet algo que resolva meu problema. Acho que essas duas funcionalidades a mais no sistema fariam toda a diferença. Desde já, muito obrigado!

**Comment by brunosantoshx** [comment]
Olá @enakonieczny, como vai?

Ambas as questões são de técnica e não de ferramenta, portanto, o correto seria pesquisar como funciona uma paginação com PHP e adaptar o conceito para o ORM e de igual forma com a pesquisa.

Para fazer a paginação você vai precisar trabalhar com os parâmetros `offset` e `limit` do PHP Activerecord. E para a pesquisa você irá usar o operador LIKE (https://www.w3schools.com/sql/sql_like.asp). 

Com estas diretrizes você já poderá desenvolver ambas as aplicações. E é muito importante que você estude o funcionamento com muita calma para que você absorva e entenda cada passo do processo porque são itens muito presentes em sistemas.

Forte abraço e sucesso sempre!
