### ISSUE TITLE
Como criptografar a senha do usuário

### ISSUE THREAD

**Issue by washingtoncardoso** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#7]
Olá @brunosantoshx!

Estou tentando fazer a parte de login, porem estou com a seguinte dúvida:

Como faço para criptografar a senha do usuário para ser comparada com a senha que está no banco? Teria que pegar a senha digitada + o salt e assim depois comparar?

**Comment by brunosantoshx** [comment]
Olá @washingtoncardoso, como vai?

Exatamente! Em código seria: 

```php
$password = \HXPHP\System\Tools::hashHX($post['password'], $user->salt);

if ($password['password'] === $user->password) {
...
}
```
