### ISSUE TITLE
Múltiplos Erros - Tutorial Numero 4

### ISSUE THREAD

**Issue by mateusjose** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#71]
Segue abaixo os erros que tento arrumar a dias mas não consigo, por favor ajudem ae.
![screenshot_error2](https://cloud.githubusercontent.com/assets/8332806/23443701/5e1e7a72-fe0f-11e6-8e17-933ab93ddbdd.png)

**Comment by brunosantoshx** [comment]
Olá @mateusjose, tudo bem?

O erro é no código mesmo, portanto, você precisa analisar com calma as linhas apontadas nestas mensagens de erro. 

Veja que a primeira mensagem aponta a linha 10 do model User e a segunda apresenta uma mensagem dizendo que a coluna `role_id` não pode receber um valor `null`. Certifique-se de validar que o valor desta coluna está sendo passado para o método `create()` e assim este erro será solucionado.

Forte abraço e sucesso sempre!
