### ISSUE TITLE
Dúvida no arquivo Services/Auth/Auth.php 

### ISSUE THREAD

**Issue by guilherme-camargo** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#74]
Bom Dia, Gostaria de esclarecer uma dúvida referente a um parâmetro que é passado as variáveis after_login e after_logout, tive alguns problemas com ela e simplesmente não sei como resolver (até então removi o parâmetro das mesmas e resolveu temporariamente), mas não sei para que serve esse parâmetro estou na aula 7 até então o que entendi é que essa parâmetro serviria para transformar ambas as variáveis em um array associativo estou certo? e se sim poderia me dar um exemplo de como isso seria possível alterar entre os after_login e o logout? como esse parâmetro seria passado?
A mensagem de erro quando deixo o parâmetro é a seguinte:

Warning: Illegal string offset 'default' in C:\wamp64\www\sistema\src\HXPHP\System\Services\Auth\Auth.php on line 5

Obrigado desde Já.

**Comment by brunosantoshx** [comment]
Olá @guilherme-camargo, boa tarde. Tudo bem?

Este bug já foi corrigido nas versões mais recentes do HXPHP. Você precisará substituir a sua pasta `src` para a atual. 

O array associativo se faz necessário, pois, uma autenticação realizada em uma subpasta não deve ser válida para outra.

Espero ter ajudado.
Forte abraço e sucesso sempre!
