### ISSUE TITLE
Error Not Found ao fazer login

### ISSUE THREAD

**Issue by FRANCISCORICARDO1910** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#75]
Bom dia Bruno
Criei um sistemas de arranchamento e na minha maquina local deu tudo certo, agora que implementei aqui no servidor apos fazer o login aparece a seguinte menssagem.

Not Found
The requested URL /sisrancho/index/logar was not found on this server.
Apache/2.2.22 (Debian) Server at 10.78.12.8 Port 80

Ja verifiquei na documentação que o modulo rewrite deveria esta ativado entao fizemos isso, mas mesmo assim continua a mesma menssagem. O que poderia ser? 

o arquivo config.php esta configurado dessa forma.

$configs->env->add('production');

        $configs->env->production->baseURI = '/sisrancho/';
        
        $configs->env->production->database->setConnectionData(array(
			'host' => 'localhost',
			'user' => 'root',
			'password' => '*****',
			'dbname' => 'sisrancho'
		));
        $configs->env->production->auth->setURLs('/sisrancho/home', '/sisrancho/index/login');

Poderia me ajudar.

**Comment by brunosantoshx** [comment]
Olá @FRANCISCORICARDO1910, boa tarde.

Você contratou um VPS? Instalou o LAMP por comando? Se sim, você precisa configurar o Apache para que o mod_rewrite funcione corretamente.

Este tipo de erro está relacionado ao Apache.
