### ISSUE TITLE
Problema ao efetuar uma requisição para o phpActiveRecord

### ISSUE THREAD

**Issue by KievMaia** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#77]
Boa noite Bruno,

Excelente curso. Bati cabeça em algumas situações, mas pesquisando aqui, e ali, consegui chegar até quase o final.
Estou na aula 10 parte 2, para hospedar o sistema, no entanto um erro quando tento fazer qualquer requisição para o banco de dados retorna.

Fatal error: in /home/u284116696/public_html/vendor/php-activerecord/php-activerecord/lib/Connection.php

Fiz, refiz a aula e nada. Pode me ajuar?

Obrigado!

**Comment by carusogabriel** [comment]
Olá

Esta classe do erro é referente a Conexão com a base de dados. Você configurou o ambiente de `production` corretamente?

Abraços

**Comment by KievMaia** [comment]
Olá Gabriel,

obrigado pela resposta.
Então amigo, eu configurei corretamente o ambiente de produção e a hospedagem.
A hospedagem é da Hostinger, abaixo o print da configuração do ambiente e também da base e usuário criados na hospedagem. Lembrando que dei permissão total para o usuário criado.

![image](https://cloud.githubusercontent.com/assets/9864866/25806513/cfdbc62e-33d9-11e7-992e-10e6f8b46360.png)
![image](https://cloud.githubusercontent.com/assets/9864866/25806537/e996e3dc-33d9-11e7-8fcb-c71b80e485b7.png)

**Comment by KievMaia** [comment]
Olá amigo, pesquisei mais um pouco e achei meu erro.
o host da hospedagem é mysql.hostinger.com.br e não localhost como havia configurado.

Mesmo assim obrigado pela dica.
Abraço.

**Comment by carusogabriel** [comment]
Olá @KievMaia

Perfeito, fico feliz que tenha sanado o seu problema!

Abraços
