### ISSUE TITLE
Problema na redefinição de senha, devido a versão do PHP.

### ISSUE THREAD

**Issue by KievMaia** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#78]
Olá amigos,

eu novamente, com uma nova dificuldade. No vídeo 11 onde o Bruno informa que foi atualizada a versão do HXPHP framework, eu tentei atualizar, porém alguns códigos requerem o php 7, ainda estou com o 5, por este motivo o sistema não rodou.

No entanto, quando comecei a seguir as vídeo aulas, baixei a última versão do projeto que segundo ele rodaria com o php 5. O que acontece é que, se eu atualizar meu PHP para a versão 7, esta versão que baixei para o php 5 continuará funcionando?

Atualmente o erro que ele informa é este do print abaixo. Há alguma forma de contorná-lo, sem precisar atualizar o php e o HXPHP framework?

![image](https://cloud.githubusercontent.com/assets/9864866/25816104/653c25b4-33f9-11e7-812f-c3d2450e02f4.png)

![image](https://cloud.githubusercontent.com/assets/9864866/25816153/8bd6a9c4-33f9-11e7-8146-218cd2d6840b.png)

Obrigado, desde já.

**Comment by carusogabriel** [comment]
@kievmedia 

De uma olhada no arquivo `index.php`, e siga as instruções para o sistema na versão 5 do php, porém, recomendo a atualização para o php 7

**Comment by KievMaia** [comment]
Olá amigo,

atualizei meu Php para a versão 7, substitui a pasta HXPHP como o Bruno orienta no vídeo 11, no entanto o mesmo erro permanece.
Já vi e revi o vídeo, e o erro permanece.

Att.

**Comment by carusogabriel** [comment]
Aquelas orientações são ultrapassadas. Novamente: acesse o arquivo `índex.php` no repositório oficial do HXPHP, e siga as instruções. É apenas um erro de incompatibilidade

**Comment by brunosantoshx** [comment]
Olá @KievMaia, como vai?

Na verdade, o que está acontecendo é um erro de sintaxe. Isto é, você digitou os códigos de forma incorreta. 

Exemplos: `site-url` seria `site_url` e `baseURI()` seria `baseURI`.

É só corrigir e continuar com os estudos.
Forte abraço e sucesso sempre!

**Comment by KievMaia** [comment]
Boa noite Bruno,

Era isso mesmo amigo!!! Muito obrigado. Seu curso é sensacional, tudo bem explicado, as vezes um pouco rápido (rsrsrrs), mas aí  a gente pausa, revê o conceito e segue o baile...kkk

Obrigado mais uma vez, e grande abraço!
