### ISSUE TITLE
Upload de Arquivos e envio de e-mail

### ISSUE THREAD

**Issue by profbaco** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#8]
Olá amigo, tudo bem? pensa em fazer uma parte referente a upload de arquivos e envio de e-mail?

**Comment by brunosantoshx** [comment]
Olá @profbaco, como vai?

Pretendo gravar uma aula extra para implementar a confirmação de e-mail, porém, quanto ao envio de arquivos, creio que isto seja assunto para uma próxima série.

Forte abraço e sucesso sempre!
