### ISSUE TITLE
Warning do ActiveRecord

### ISSUE THREAD

**Issue by lukisamk** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#82]
## Olá!

Estou aprendendo PHP e já estou utilizando seu framework em um projeto pessoal, e estou gostando muito! O problema é que há um warning referente ao ActiveRecord\DateTime que aparece em todas as páginas!

![image](https://cloud.githubusercontent.com/assets/28795323/26228604/728df3ee-3c11-11e7-8711-d54f304644c1.png)

O que faço?

Desde já agradeço a ajuda!

**Comment by flemej** [comment]
Parece ser diferença de regionalização. O dado chega a ser Gravado na tabela?

**Comment by lukisamk** [comment]
Não, não funciona nada =/

**Comment by brunosantoshx** [comment]
Olá @lukisamk e @flemej, boa noite. Tudo bem?

Esse problema era no PHP Activerecord com PHP 7, mas, já foi corrigido: https://github.com/jpfuentes2/php-activerecord/pull/568. Recomendo apagar a pasta `vendor` e o arquivo `composer.lock` e rodar o comando `composer install`.

Forte abraço e sucesso sempre!
