### ISSUE TITLE
Como recuperar o descrição da role para a view usuarios?

### ISSUE THREAD

**Issue by flemej** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#84]
Olá!
Estou tentando retornar a descrição do status do user na tela de atualização de usuarios do admin (aula 17) mas não estou conseguindo acessar a o dado.
Meu código está assim:

class UsuariosController extends \HXPHP\System\Controller {
    public function __construct($configs)
    {
        parent::__construct($configs);
        $this->load('Services\Auth', $configs->auth->after_login, $configs->auth->after_logout, true);
        $userId = $this->auth->getUserId();
        $user = User::find($userId);
        $role = Role::find($user->role_id);
        $this->auth->redirectCheck();
        $this->auth->roleCheck(array('admin'));
        $this->load('Helpers\Menu', $this->request, $this->configs, $role->role);
        $this->view->setTitle(Defaults::NOME_SISTEMA . ' - Cadastro de usuários')
          ->setVars([
          'user' => $user,
          'users' => User::all()
          ]);
    }
}

class User extends \HXPHP\System\Model {
    static $belongs_to = array(
        array('role'),
        array('statusUser'));

class statusUser extends \HXPHP\System\Model {
    static $has_many = array(array('user'));
}

No index, isso dá certo:
    echo $user->role->role;
Mas isso, não:
    echo $user->statusUser->desc;

A tabela está criada no banco com o nome status_users e tem relacionamento com a tabela users (conforme modelo do curso).
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `image` VARCHAR(40) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `users_role_id_idx` (`role_id` ASC),
  INDEX `users_status_users_idx` (`status` ASC),
  CONSTRAINT `users_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mercurio`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_status_users`
    FOREIGN KEY (`status`)
    REFERENCES `mercurio`.`status_users` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8

CREATE TABLE IF NOT EXISTS `status_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` INT(1) NOT NULL,
  `desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `status_user_status_idx` (`status` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
KEY_BLOCK_SIZE = 1

O que está faltando?
Por favor, ajudem! 
Obrigado! :)

**Comment by flemej** [comment]
Fiz o upload para o server de produção e está dando o seguinte erro:
Fatal error: Uncaught ReflectionException: Class \Statususer does not exist in /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Reflections.php:33 Stack trace: #0 /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Reflections.php(33): ReflectionClass->__construct('\\Statususer') #1 /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Relationship.php(295): ActiveRecord\Reflections->add('\\Statususer') #2 /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Relationship.php(286): ActiveRecord\AbstractRelationship->set_class_name('\\Statususer') #3 /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Relationship.php(693): ActiveRecord\AbstractRelationship->set_inferred_class_name() #4 /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Table.php(533): ActiveRecord\BelongsTo->__construct(Array) #5 /home/u680476950/public_html/Mercurio/vendo in /home/u680476950/public_html/Mercurio/vendor/php-activerecord/php-activerecord/lib/Reflections.php on line 33

No ambiente local funciona corretamente. 
Será um problema relacionado?
Obrigado!

**Comment by Davidsonc** [comment]
encontrou a solução para esse problema ?
