### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by davidsonclem** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#85]
Bruno, boa noite!

Fiz um download de um template  para dashboard, como faço para substituir esse css?

**Comment by brunosantoshx** [comment]
Olá @davidsonclem, boa noite. Tudo bem?

Ué, normalmente! Primeiramente, desmembre o template e atualize o header e footer da pasta das views. Depois, mova todos os scripts, imagens e estilos para a pasta public. O ideal é que as demais views sejam o miolo, isto é, você precisa dividir com precisão o header e footer para encaixar as views corretamente. Sobre os menus: anote todas as classes e configure no app/config.php. 

É um pouco trabalhoso na primeira vez, mas, depois de feito, você se acostuma e vira algo bem tranquilo.

Forte abraço e sucesso sempre!
