### ISSUE TITLE
Como alterar o dado de um atributo foreign key (PHP ActiveRecord)?

### ISSUE THREAD

**Issue by itallosilva** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#86]
Olá, assisti todo o tutorial e estou aproveitando a parte do sistema de cadastro e login em um projeto que estou desenvolvendo.
No momento surgiu um problema quanto a atualização de dados de uma das tabelas que tenho. 
Estou tentando atualizar um dado que é uma chave estrangeira, porém não está atualizando.

Alguém teria noção de como fazer para alterar o dado sendo o atributo uma chave estrangeira?

**Comment by flemej** [comment]
Olá! 

Deixe mais detalhes pra gente poder analisar!

**Comment by itallosilva** [comment]
Resumindo um pouco o projeto...

Cada usuário poderá cadastrar vários clientes e cada cliente poderá ter vários projetos.

Tenho a tabela Users, Clients e Projects.

A tabela Projects possui os seguintes atributos:
id, cliente (nome do cliente), status, endereco, data_alteracao, client_id (foreign key), user_id (foreign key)

Ao tentar editar os dados da tabela Projects, não estou conseguindo alterar client_id. Os demais dados eu consigo alterar.

`	public static function atualizar($project_id, $user_id, array $post)
	{
		$callbackObj = new \stdClass;
		$callbackObj->client = null;
                $callbackObj->project = null;
		$callbackObj->status = false;
		$callbackObj->errors = array();
                
                $client = Client::find('first', array('name' => $post['cliente'], 'user_id' => $user_id));                
                
		$project = self::find($project_id);
                $project->cliente = $client->name;                
                $project->status = $post['status'];
                $project->endereco = $post['endereco'];
                $project->client_id = $client->id;
                $data = date("Y-m-d");
                $project->data_alteracao = $data;
                 
                $atualizarProject = $project->save(false);
                
		if ($atualizarProject) {
                    $callbackObj->client = $client;
                    $callbackObj->project = $project;                                             
                    $callbackObj->status = true;
                    return $callbackObj;
		}

		$errors = $atualizarProject->errors->get_raw_errors();

		foreach ($errors as $field => $message) {
			array_push($callbackObj->errors, $message[0]);
		}

		return $callbackObj;
	}`

**Comment by itallosilva** [comment]
Resumindo um pouco o projeto...

Cada usuário poderá cadastrar vários clientes e cada cliente poderá ter vários projetos.

Tenho a tabela Users, Clients e Projects.

A tabela Projects possui os seguintes atributos:
id, cliente (nome do cliente), status, endereco, data_alteracao, client_id (foreign key), user_id (foreign key)

Ao tentar editar os dados da tabela Projects, não estou conseguindo alterar client_id. Os demais dados eu consigo alterar.

```
public static function atualizar($project_id, $user_id, array $post)
{
$callbackObj = new \stdClass;
$callbackObj->client = null;
$callbackObj->project = null;
$callbackObj->status = false;
$callbackObj->errors = array();

            $client = Client::find('first', array('name' => $post['cliente'], 'user_id' => $user_id));                
            
	$project = self::find($project_id);
            $project->cliente = $client->name;                
            $project->status = $post['status'];
            $project->endereco = $post['endereco'];
            $project->client_id = $client->id;
            $data = date("Y-m-d");
            $project->data_alteracao = $data;
             
            $atualizarProject = $project->save(false);
            
	if ($atualizarProject) {
                $callbackObj->client = $client;
                $callbackObj->project = $project;                                             
                $callbackObj->status = true;
                return $callbackObj;
	}

	$errors = $atualizarProject->errors->get_raw_errors();

	foreach ($errors as $field => $message) {
		array_push($callbackObj->errors, $message[0]);
	}

	return $callbackObj;
}
```

**Comment by flemej** [comment]
Qual a mensagem de erro que está ocorrendo?

**Comment by itallosilva** [comment]
Não está aparecendo mensagem de erro. Simplesmente não altera os dados.

**Comment by flemej** [comment]
Italo, 
O objeto que você setou ($callbackObj->errors) tem a informação sobre erro que está ocorrendo. 
Adicione a linha "var_dump($callbackObj->errors);" antes do return da condição de erro e posta o que saiu aqui pra gente

**Comment by itallosilva** [comment]
O $callbackObj->errors está null. :/
Não achei nada na internet. Complicou.

**Comment by flemej** [comment]
Essa linha  funciona? 
  $project->cliente = $client->name;

**Comment by itallosilva** [comment]
Se eu mantiver a linha $project->client_id = $client->id, não funciona, mas se eu comentar essa linha, funciona.

**Comment by flemej** [comment]
As suas tabelas estão criadas em innodb? 
Eu tive um erro parecido com esse e penei pra descobrir que o meu web hosting free trocou o storage engine e o novo teve problemas com o phpActiveRecord. Em casa, no workbench funcionava normal mas no web hosting dava pau. 
Faz um teste... Desabilita a chave estrangeira da tabela projeto com a cliente e tenta gravar o registro. Se der certo e se o motor de armazenamento atual não for innodb, troque o motor (de todas as tabelas) para innodb, habilite a fk e refaça o teste. 
Se nada disso funcionar e se o @brunosantoshx ou outra pessoa não detectar nenhum problema no core ou no codigo, pode complicar porque aparentemente o suporte do phpActiveRecord 'is dead'. Tem um cara com o mesmo problema que você (http://www.phpactiverecord.org/boards/4/topics/2067-cannot-change-primary_key) postado faz 5 meses e não tem resposta. A postagem mais recente dos caras é de 5 anos atrás! 
(http://www.phpactiverecord.org/news/6-website-downtime)  
Boa sorte aí no teste e avisa a gente do resultado. 
Valeu!

**Comment by flemej** [comment]
Obs: o problema do cara que mencionei é parecido. No caso dele, ele quer dar update na pk e não na fk.

**Comment by itallosilva** [comment]
Consegui!! O problema não estava no código, mas sim na tabela MySQL. Criei a tabela e coloquei a foreign key como primary key. Criei a tabela novamente e retirei isso aí consegui alterar. Já estava ficando louco. kkkk
Obrigado pela predisposição em ajudar.

```
CREATE TABLE IF NOT EXISTS `iengenharia`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `client_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `data_alteracao` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `projects_client_id_idx` (`client_id` ASC),
  INDEX `projects_user_id_idx` (`user_id` ASC),
  CONSTRAINT `projects_client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `iengenharia`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `projects_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `iengenharia`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
```

**Comment by flemej** [comment]
Boa, cara! Era o maledeto do innodb mesmo.... Kkkkk
Qq coisa estamos aí :)
