### ISSUE TITLE
Como seria a maneira correta de se criar uma listagem ?

### ISSUE THREAD

**Issue by Davidsonc** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#87]
@brunosantoshx  Estou satisfeitíssimo com o HXPHP e estou admirado com a sua experiencia e inteligencia exibida inclusive nas aulas das quais eu acho a didática excelente, parabéns!!! Gostaria de frizar que sei como fazer tudo que vou peguntar aqui mas à moda antiga, com muito html e javascript e vira aquela bagunça, gostaria de saber como fazer uma listagem de usuários com os ícones exibir, editar e excluir nas linhas da listagem... outra coisa que gostaria de saber é como trabalhar com modais dentro do hxphp, ajax ou me perdoem mas sou do tempo do window.open e frames, essa pergunta é justamente para me aperfeiçoar e tornar o código mais elegante!

**Comment by brunosantoshx** [comment]
Olá @Davidsonc, boa tarde. Como vai?

Recebi também seu e-mail e vou aproveitar a deixa para responder por aqui! Até alguns meses eu era sócio de duas agências e trabalhava de domingo a domingo quase que 14 horas por dia. Além de liderar e gerenciar os projetos das minhas agências, ainda prestava consultoria para outras e o resultado é uma indisponibilidade absurda!

Decidimos encerrar as agências e migrar de ramo. Agora sou sócio e líder de projetos em uma startup e estou lutando para encerrar os projetos das agências. A minha disponibilidade para gerenciar o canal e/ou o HXPHP é quase que zero, pelo menos neste ano. 

Pretendo retomar ao projeto quando as coisas se acalmarem. Este período tem sido sensacional! Estou aprendendo várias novas ferramentas e muita coisa de infra e DevOps. 

Em uma possível volta ao canal, os conteúdos seriam ainda mais refinados do que atualmente!

É isto, amigo!
Abração e sucesso sempre!

**Comment by brunosantoshx** [comment]
Sobre sua dúvida: 

Recomendo você usar AngularJS junto ao HXPHP para desenvolver sistemas modernos e escaláveis. 

O uso de AJAX com jQuery para manipular DOM é bem estressante e confuso, portanto, o uso do Angular vai te ajudar a produzir códigos reutilizáveis e de qualidade! 

O segredo para respostas de JSON é setar uma view vazia e desativar a inclusão de header e footer! Ex:

Crie uma pasta:
+ `app/views/blank`

Crie uma view vazia:
+ `app/views/blank/blank.phtml`

Configure a action de resposta desta forma:
```php
public function listarUsuariosAction()
{
$this->view->setTemplate(false)->setPath('blank')->setFile('blank');

echo json_encode($response);
}
```
