### ISSUE TITLE
Erro aviso quando digito SENHA INCORRETA

### ISSUE THREAD

**Issue by lucas1360** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#88]
! ) Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-11-13 08:59:21 BRST' for column 'created_at' at row 1' in C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 336
( ! ) ActiveRecord\DatabaseException: exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-11-13 08:59:21 BRST' for column 'created_at' at row 1' in C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php:333 Stack trace: #0 C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(333): PDOStatement->execute(Array) #1 C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(359): ActiveRecord\Connection->query('INSERT INTO `lo...', Array) #2 C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php(844): ActiveRecord\Table->insert(Array) #3 C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php(799): ActiveRecord\Model->insert(true) #4 C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php(780): ActiveRecord\Model->save(true) #5 C:\wamp64\www\sistema\app\models\LoginAttempt.php(19): ActiveRecord\Model::create(Array) #6 C:\wamp64\www\sistema\app\models\User.php(168): LoginAttempt::RegistrarTentativa(1) #7 C:\wamp64\www\sistema\app\controllers\LoginController.php(31): User::login(Array) #8 [internal function]: LoginController->logarAction() #9 C:\wamp64\www\sistema\src\HXPHP\System\App.php(103): call_user_func_array(Array, Array) #10 C:\wamp64\www\sistema\index.php(36): HXPHP\System\App->run() #11 {main} in C:\wamp64\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 336

Call Stack
#	Time	Memory	Function	Location
1	0.0015	251048	{main}( )	...\index.php:0
2	0.1272	2042864	HXPHP\System\App->run( )	...\index.php:36
3	0.1518	2203360	call_user_func_array:{C:\wamp64\www\sistema\src\HXPHP\System\App.php:103} ( )	...\App.php:103
4	0.1518	2203984	LoginController->logarAction( )	...\App.php:103
5	0.1604	2323880	User::login( )	...\LoginController.php:31
6	0.2965	2727568	LoginAttempt::RegistrarTentativa( )	...\User.php:168
7	0.2966	2727904	ActiveRecord\Model::create( )	...\LoginAttempt.php:19
8	0.2973	2730304	ActiveRecord\Model->save( )	...\Model.php:780
9	0.2973	2730912	ActiveRecord\Model->insert( )	...\Model.php:799
10	0.3043	2902184	ActiveRecord\Table->insert( )	...\Model.php:844
11	0.3057	2905344	ActiveRecord\Connection->query( )	...\Table.php:359

**Comment by flemej** [comment]
Incluir o seguinte comando no arquivo configs. Php:
ActiveRecord\Connection::$datetime_format = 'Y-m-d H:i:s';
