### ISSUE TITLE
Problema relacionado na aula 7. Não salva o usuário e se tenta entrar novamente em /cadastro entra normalmente.

### ISSUE THREAD

**Issue by specialbuilds** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#89]
Ao se cadastrar o usuário é redirecionado para o /home/ mas ao tentar entrar em /cadastro/ para tentar redirecionar, o sistema entende como se não estivesse logado e não redireciona.

**Comment by flemej** [comment]
@specialbuilds , o seu construtor da classe CadastroController deve estar parecido com este:

	public function __construct($configs)
	{
		parent::__construct($configs);

		$this->load(
			'Services\Auth',
			$configs->auth->after_login,
			$configs->auth->after_logout,
			true
		);

		$this->auth->redirectCheck(true);
	}
Verifique e me fale se funcionou.
Abraço!
