### ISSUE TITLE
Logando o usuário

### ISSUE THREAD

**Issue by rodrigoalbinoh** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#9]
Boa noite,

estou com problemas para criar as funções e afins para logar o usuário. Já li a documentação várias vezes e também sobre o PHP Active record e documentação do próprio php, mas ainda possuo dificuldade. 
A série terá continuidade? 
Consegui logar e deslogar o usuário em uma vez, nas outras não obtive sucesso. Não consigo fazer as ligações com as tabelas Roles para identificar os níveis de acesso e muito menos a login_attempts para bloquear a senha do usuário caso atinja um número x de tentativas de login. 
Não importa o quanto eu tente, sempre tenho dificuldades de aprender, apesar de amar muito programar e criar.

Agradeço a atenção.

**Comment by brunosantoshx** [comment]
Olá @rodrigoalbinoh, como vai?

A série, com certeza, irá continuar! Eu tive alguns problemas pessoais, a casa estava em obras e com ruídos constantes, agora estou com muitas outras responsabilidades profissionais, porém a série será concluída e as aulas serão publicadas às quinta-feiras, como de costume. 

Aconselho esperar só mais um pouco que tratarei todas estas questões durante a série e assim poderá fazer tudo funcionar perfeitamente.

Ainda neste mês já publicaria a próxima aula da série e pretendo fazê-la bem completa para recuperarmos o ânimo.

Forte abraço e sucesso sempre!
