### ISSUE TITLE
Problema na criação do editarAction no perfil do Administrador

### ISSUE THREAD

**Issue by NajaraCarioca** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#90]
Estou com problemas na criação dessa action, não consigo fazer com que no formulário apareça as informações do usuário especifico que eu quero editar, no sistema está passando o id porém no formulário preenche com os dados do usuário autenticado e gostaria de saber aonde estou errando.

**Comment by flemej** [comment]
Poste seu código pra gente tentar ajudar!
