### ISSUE TITLE
Ocorrência de Warning após logar o usuário.

### ISSUE THREAD

**Issue by valervl** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#91]
Está ocorrendo esse Warning após a autenticação de usuário:
 
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\ProtocoloSistema\vendor\php-activerecord\php-activerecord\lib\Model.php on line 1670

**Comment by flemej** [comment]
Poste seu código aqui pra gente tentar ajudar!

**Comment by valervl** [comment]
Todo o código está aqui:
https://github.com/valervl/projetomvc.git

**Comment by Mikesuper666** [comment]
para mim aprece o mesmo erro

**Comment by flemej** [comment]
@valervl , dei uma olhada no seu código e percebi que no seu construtor do LoginController está faltando o load do helper para o menu.
Inclua a seguinte linha no construtor:
$this->load('Helpers\Menu', $this->request, $this->configs);        
Depois me diga se resolveu.
![image](https://user-images.githubusercontent.com/18681996/35367305-d8dd5022-0164-11e8-989a-7802c301cdcd.png)

Abraço!

**Comment by valervl** [comment]
Deixei o código dessa forma:

class LoginController extends \HXPHP\System\Controller
{
	public function __construct($configs)
	{
		parent::__construct($configs);

		$this->load('Helpers\Menu', $this->request, $this->configs);

		$this->load(
			'Services\Auth',
			$configs->auth->after_login,
			$configs->auth->after_logout,
			true
		);
		
	}

E não resolveu.

**Comment by flemej** [comment]
Mesmo erro?

**Comment by valervl** [comment]
![capturar](https://user-images.githubusercontent.com/35313085/35368719-12905788-015b-11e8-99a4-7c81f932c3fa.PNG)
Mesmo Erro.

**Comment by flemej** [comment]
Que estranho...
Quando eu rodei o composer no seu Código, deu alguns paus no autoloader. Como eu tenho o framework instalado aqui, só copiei e colei a pasta "vendor" do meu para o seu projeto, daí começou a dar pau por falta do módulo de menu então eu resolvi colocando aquela linha que te passei. Funcionou redondo!
Sugiro você verificar se está tudo certinho no seu composer e, caso esteja, na sua modelagem de dados.
Este erro se refere a uma tentativa de contar um objeto não contável.

http://php.net/manual/en/function.count.php

**Comment by brunosantoshx** [comment]
Fala galera, tudo bem?

Esse erro ocorre na versão 7.2 do PHP em alguns conflitos usando a função `count()`. Isto é, nem todos os pacotes encontram-se totalmente compatíveis com esta nova versão e acabam gerando estes warnings.

Creio que os pacotes já devem ter sido ajustados, portanto, rodando o comando `composer update` é de se esperar que o problema seja fixado. Porém, caso persista, você pode mudar para a versão 7.1 que o problema será resolvido.

Forte abraço e sucesso sempre!
