### ISSUE TITLE
cadastrar

### ISSUE THREAD

**Issue by pissechihale** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#94]
Uncaught Error: Class 'U_profile' not found 
quando corro a action, mas reconhece no controller

**Comment by brunosantoshx** [comment]
Olá @pissechihale, tudo bem? 

Essa classe seria um model? Se sim, creio que o problema seja a falta de padrão na nomenclatura, pois, assim o autoload não irá ser aplicado. Caso seja alguma classe customizada, lembre-se de dar o use corretamente com o namespace completo. 

Seguindo estes passos é certeza de que dará tudo certo.

Forte abraço e sucesso sempre!
