### ISSUE TITLE
Problema no hxphp 

### ISSUE THREAD

**Issue by nadojba** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#95]
instalei, segui todos passos, e ta dando esse erro no painel home

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xamppp\htdocs\painel\vendor\php-activerecord\php-activerecord\lib\Model.php on line 1670

**Comment by brunosantoshx** [comment]
Olá @nadojba, tudo bem? 

Recomendo você tentar usar o `composer update`, pois, trata-se de um problema de compatabilidade do PHP Activerecord com a versão 7.2 do PHP.

Caso o `composer update` não resolva, recomendo mudar para a versão 7.1 do PHP que encontra-se mais compatível com a maioria dos pacotes.

Forte abraço e sucesso sempre!
