### ISSUE TITLE
erro ou configurar o Request

### ISSUE THREAD

**Issue by MarckVinny** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#96]
O Request não está funcionando comigo estou com a versão mais recente instalada "3.0" e já tentei varias vezes configurar mas não consigo segue parte do cód. com o erro. `$this->request = new Http\Request($configs->baseURI);`

    public function setConfigs(Config $configs, string $subfolder, string $controller, string $action)
    {
        /*
         * Injeção das Configurações
         * @var object
         */
        $this->configs = $configs;
 
        $this->request = new Http\Request($configs->baseURI);
 
        /*
         * Subfolder
         * @var mixed
         */
        $this->subfolder = $subfolder;
 
        /**
         * Tratamento das variáveis.
         */
        $controller = strtolower(str_replace('Controller', '', $controller));
        $action = ($controller == $configs->controllers->notFound ? 'indexAction' : $action);
        $action = str_replace('Action', '', $action);
 
        /**
         * Verifica se os valores padrão foram alterados no construtor do Controller.
         */
        $view_settings = new \stdClass();
 
        $default_values = [

Arguments
"Class 'HXPHP\System\View\Http\Request' not found"

Estou configurando dentro do \View\Core.php mas a pasta do Http está fora da view e não consigo apontar para ela não sei se seria esse o problema, preciso de ajuda.
       ```
 /*
         * Injeção das Configurações
         * @var object
         */
        $this->configs = $configs;

        $this->request = new Http\Request($configs->baseURI);

        /*
         * Subfolder
         * @var mixed
         */
        $this->subfolder = $subfolder;
```

**Comment by brunosantoshx** [comment]
Olá @MarckVinny, tudo bem?

O framework foi atualizado e na nova versão esse bug foi corrigido.

Forte abraço e sucesso sempre!
