### ISSUE TITLE
Erro de syntax AULA #8

### ISSUE THREAD

**Issue by MarckVinny** [brunosantoshx/serie-criando-sistema-de-cadastro-e-login#97]
Olá Bruno, estou tendo um erro de syntax(não sei por qual motivo) pois segui a risca e conferi várias vezes em (video 19:25) vc faz o teste de login e é justamente nesse momento do teste que aparece esse erro pra mim.
"
public static function login(array $post) 
{
    $user = self::find_by_username($post['username']);
 
    if (!is_null($user) {
        $password = \HXPHP\System\Tools::hashHX($post['password'], $user->salt);
 
        if (loginAttempt::existemTentativas($user->password)){
            if ($password['password'] === $user->password) {
 
                var_dump('logado');
                loginAttempt::limparTentativas($user_id);
            }
            else {
                loginAttempt::registrarTentativas($user_id);
            }
        }
    }
}
 (abaixo segue o erro de syntax)
Arguments
"syntax error, unexpected 'public' (T_PUBLIC), expecting end of file"
"
Está escrito igual ao video e não sei o que pode estar ocorrendo de errado.
PS.: estou com a versão mais atual 3.0
![image](https://user-images.githubusercontent.com/36089190/50406453-79c16e80-07ac-11e9-9778-319910795a5b.png)

**Comment by brunosantoshx** [comment]
Olá @MarckVinny, tudo bem?

Aparentemente você adicionou uma `}` a mais que está fechando a classe e, por conta disto, considera o método como um erro por estar fora da classe.

Por favor, revise todas as chaves com calma e tente usar IDE para te ajudar a encontrar esse erro. Provavelmente a chave extra está no método anterior.

Forte abraço e sucesso sempre!
